# Build stage - builds both jonnify server and flyer CLI
FROM golang:1.25-alpine AS builder

# Install tar for creating distribution archives
RUN apk --no-cache add tar

WORKDIR /build

# ===== Build jonnify server =====
COPY go.mod go.sum* ./
RUN go mod download

COPY main.go .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o jonnify .

# ===== Build flyer CLI =====
WORKDIR /build/flyer
COPY flyer/go.mod flyer/go.sum ./
RUN go mod download

COPY flyer/ .

# Extract version from source
RUN FLYER_VERSION=$(grep 'version = ' cmd/flyer/main.go | cut -d'"' -f2) && \
    echo "${FLYER_VERSION}" > /build/flyer-version.txt && \
    echo "Building flyer v${FLYER_VERSION} for linux, windows, darwin (amd64)"

# Build flyer for Linux amd64
RUN FLYER_VERSION=$(cat /build/flyer-version.txt) && \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
        -ldflags="-s -w -X main.version=${FLYER_VERSION}" \
        -o /build/flyer-linux-amd64 ./cmd/flyer

# Build flyer for Windows amd64
RUN FLYER_VERSION=$(cat /build/flyer-version.txt) && \
    CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build \
        -ldflags="-s -w -X main.version=${FLYER_VERSION}" \
        -o /build/flyer-windows-amd64.exe ./cmd/flyer

# Build flyer for Darwin (macOS) amd64
RUN FLYER_VERSION=$(cat /build/flyer-version.txt) && \
    CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build \
        -ldflags="-s -w -X main.version=${FLYER_VERSION}" \
        -o /build/flyer-darwin-amd64 ./cmd/flyer

# Create distribution tarballs for all platforms
RUN FLYER_VERSION=$(cat /build/flyer-version.txt) && \
    mkdir -p /build/distr/flyer && \
    # Linux
    tar -czvf /build/distr/flyer/flyer-${FLYER_VERSION}-linux-amd64.tar.gz \
        -C /build flyer-linux-amd64 && \
    # Windows
    tar -czvf /build/distr/flyer/flyer-${FLYER_VERSION}-windows-amd64.tar.gz \
        -C /build flyer-windows-amd64.exe && \
    # Darwin
    tar -czvf /build/distr/flyer/flyer-${FLYER_VERSION}-darwin-amd64.tar.gz \
        -C /build flyer-darwin-amd64 && \
    # Create latest symlinks
    ln -sf flyer-${FLYER_VERSION}-linux-amd64.tar.gz /build/distr/flyer/flyer-latest-linux-amd64.tar.gz && \
    ln -sf flyer-${FLYER_VERSION}-windows-amd64.tar.gz /build/distr/flyer/flyer-latest-windows-amd64.tar.gz && \
    ln -sf flyer-${FLYER_VERSION}-darwin-amd64.tar.gz /build/distr/flyer/flyer-latest-darwin-amd64.tar.gz

# ===== Runtime stage =====
FROM alpine:3.19

RUN apk --no-cache add ca-certificates

WORKDIR /app

# Copy jonnify server binary
COPY --from=builder /build/jonnify /app/jonnify

# Copy the lightweight landing-hub index.html served at "/"
# (the heavy three.js 3D map lives at /map via "COPY map/" below)
COPY html/index.html /app/html/index.html

# Copy standalone emoji memory game served at "/game"
COPY html/game.html /app/html/game.html

# Copy standalone two-course index (Elixir + Agile Agent Workflow) served at
# "/courses" — unlinked from the home page, reachable by direct URL only
COPY html/courses.html /app/html/courses.html

# Copy the Health course (folder tree → /health/<chapter>/<module>; JSON probe is /healthz)
COPY html/health/ /app/html/health/

# Copy SEO files (pre-generated by `make sitemap`) served at "/sitemap.xml" and "/robots.txt"
COPY html/sitemap.xml /app/html/sitemap.xml
COPY html/robots.txt /app/html/robots.txt
# Copy the llms.txt site map (llmstxt.org convention) served verbatim at "/llms.txt"
COPY html/llms.txt /app/html/llms.txt

# Copy EGE course materials served under /ege/*
COPY html/ege/ /app/html/ege/

# Copy EDU course materials served under /edu/*
COPY html/edu/ /app/html/edu/

# Copy SCHOOL course materials served under /school/*
COPY html/school/ /app/html/school/

# Copy FUTURE course materials served under /future/*
COPY html/future/ /app/html/future/

# Copy the Elixir course (folder tree with subfolders) served under /elixir/*
COPY elixir/ /app/elixir/

# Copy the Logic course (folder tree → /logic/<chapter>/<module>) served under /logic/*
COPY html/logic/ /app/html/logic/

# Copy the Law course (folder tree → /law/<chapter>/<module>) served under /law/*
COPY html/law/ /app/html/law/

# Copy the Physics course (folder tree → /physics/<chapter>/<module>) served under /physics/*
COPY html/physics/ /app/html/physics/

# Copy the AI-at-work course (folder tree → /ai-rabota/<chapter>/<module>) served under /ai-rabota/*
COPY html/ai-rabota/ /app/html/ai-rabota/

# Copy the Agile Agent Workflow course (folder tree) served under /agile-agent-workflow/*
COPY html/agile-agent-workflow/ /app/html/agile-agent-workflow/

# Copy the 3D orbital knowledge map (three.js WebGL node-graph) served under /map
COPY html/map/ /app/html/map/

# Copy styled HTML error pages (<status>.html) served by the central error
# handler — e.g. 404.html for unmatched routes, 500.html for panics.
COPY html/error/ /app/html/error/

# Copy vendored front-end modules (three.js) served under /vendor/* — self-hosted
# so the 3D landing page has no runtime CDN dependency. The source dir is named
# "assets" (not "vendor", which Go reserves at the module root).
COPY html/assets/ /app/html/assets/

# Create distribution directory structure
RUN mkdir -p /app/distr/litestream /app/distr/flyer

# Copy litestream distribution (static, never changes)
COPY data/litestream-0.5.5.tar.gz /app/distr/litestream/

# Copy flyer distribution (built at Docker build time)
COPY --from=builder /build/distr/flyer/ /app/distr/flyer/

EXPOSE 8080

CMD ["/app/jonnify"]
