// main.go - Jonnify Edge Server
// Serves static distribution files (litestream, flyer)
package main

import (
	"errors"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/fiber/v2/middleware/recover"
)

var (
	version   = "0.1.0"
	distrDir  = "/app/distr"
	indexHTML = "/app/index.html"
	egeDir    = "/app/ege"
	eduDir    = "/app/edu"
	schoolDir = "/app/school"
	futureDir = "/app/future"
	mapDir    = "/app/map"
	// Elixir course content. FOLDER-routed (see serveElixir), unlike the flat
	// <name>.html sections above: a clean URL maps to a path under this dir and
	// resolves to <path>/index.html (directories) or <path>.html (leaf URLs).
	elixirDir = "/app/elixir"
	gameHTML  = "/app/game.html"
	// Human-facing HTML status page served at /health. The machine liveness probe
	// (JSON) is the separate /healthz route. HEALTH_HTML env-overridable.
	healthHTML = "/app/health.html"
	// On-disk dir for files served at the /vendor/* URL. Named "assets" (NOT
	// "vendor") because a vendor/ dir at the Go module root is reserved by the
	// toolchain (it forces vendor-mode builds).
	vendorDir = "/app/assets"
	// Dir of styled HTML error pages named <status>.html (404.html, 500.html, …).
	errorDir = "/app/error"
	// SEO files, pre-generated by `make sitemap` (cmd/sitemap) and baked into the
	// image; served as-is at /sitemap.xml and /robots.txt.
	sitemapXML = "/app/sitemap.xml"
	robotsTxt  = "/app/robots.txt"
)

// errorPages caches the custom HTML error pages by HTTP status code, loaded
// once at startup. A code absent from the map falls back to a JSON error. It is
// only written before app.Listen and only read thereafter, so no locking.
var errorPages = map[int][]byte{}

func main() {
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	// Allow override for local dev
	if dir := os.Getenv("DISTR_DIR"); dir != "" {
		distrDir = dir
	}
	if path := os.Getenv("INDEX_HTML"); path != "" {
		indexHTML = path
	}
	if dir := os.Getenv("EGE_DIR"); dir != "" {
		egeDir = dir
	}
	if dir := os.Getenv("EDU_DIR"); dir != "" {
		eduDir = dir
	}
	if dir := os.Getenv("SCHOOL_DIR"); dir != "" {
		schoolDir = dir
	}
	if dir := os.Getenv("FUTURE_DIR"); dir != "" {
		futureDir = dir
	}
	if dir := os.Getenv("MAP_DIR"); dir != "" {
		mapDir = dir
	}
	if dir := os.Getenv("ELIXIR_DIR"); dir != "" {
		elixirDir = dir
	}
	if path := os.Getenv("GAME_HTML"); path != "" {
		gameHTML = path
	}
	if path := os.Getenv("HEALTH_HTML"); path != "" {
		healthHTML = path
	}
	if dir := os.Getenv("VENDOR_DIR"); dir != "" {
		vendorDir = dir
	}
	if dir := os.Getenv("ERROR_DIR"); dir != "" {
		errorDir = dir
	}
	if path := os.Getenv("SITEMAP_XML"); path != "" {
		sitemapXML = path
	}
	if path := os.Getenv("ROBOTS_TXT"); path != "" {
		robotsTxt = path
	}

	// Load styled error pages into memory once (env overrides are already applied).
	errorPages = loadErrorPages(errorDir)

	app := fiber.New(fiber.Config{
		AppName:               "jonnify",
		DisableStartupMessage: false,
		// Central error handler: unmatched routes (Fiber's auto-404), panics caught
		// by the recover middleware, and every fiber.NewError returned by a handler
		// all funnel here, so error responses are rendered in exactly one place.
		ErrorHandler: func(c *fiber.Ctx, err error) error {
			code := fiber.StatusInternalServerError
			msg := err.Error()
			var fe *fiber.Error
			if errors.As(err, &fe) {
				code = fe.Code
				msg = fe.Message
			}
			return renderError(c, code, msg)
		},
	})

	// Middleware
	app.Use(recover.New())
	app.Use(logger.New(logger.Config{
		Format: "[${time}] ${status} ${method} ${path} ${latency}\n",
	}))

	// Machine liveness probe — JSON, always. Fly's [[http_service.checks]] polls
	// this (path = "/healthz" in fly.toml); it MUST keep returning 200 JSON or
	// machines/deploys are marked unhealthy.
	app.Get("/healthz", func(c *fiber.Ctx) error {
		return c.JSON(fiber.Map{"status": "ok", "version": version})
	})

	// Human-facing HTML status page at /health (the machine probe is /healthz).
	app.Get("/health", func(c *fiber.Ctx) error {
		if _, err := os.Stat(healthHTML); err != nil {
			return fiber.NewError(fiber.StatusNotFound, "health page not found")
		}
		c.Set("Cache-Control", "public, max-age=300, must-revalidate")
		return c.SendFile(healthHTML)
	})

	// SEO: sitemap.xml + robots.txt, pre-generated by `make sitemap` (cmd/sitemap)
	// and baked into the image. Content-Type is set explicitly because crawlers are
	// strict about it; the file is otherwise served verbatim like any other asset.
	app.Get("/sitemap.xml", func(c *fiber.Ctx) error {
		if _, err := os.Stat(sitemapXML); err != nil {
			return fiber.NewError(fiber.StatusNotFound, "sitemap not found")
		}
		c.Set("Content-Type", "application/xml; charset=utf-8")
		c.Set("Cache-Control", "public, max-age=3600, must-revalidate")
		return c.SendFile(sitemapXML)
	})
	app.Get("/robots.txt", func(c *fiber.Ctx) error {
		if _, err := os.Stat(robotsTxt); err != nil {
			return fiber.NewError(fiber.StatusNotFound, "robots.txt not found")
		}
		c.Set("Content-Type", "text/plain; charset=utf-8")
		c.Set("Cache-Control", "public, max-age=3600, must-revalidate")
		return c.SendFile(robotsTxt)
	})

	// Serve index.html at root
	app.Get("/", func(c *fiber.Ctx) error {
		// Match the explicit caching policy of every other content route so
		// browsers revalidate after 5 min instead of falling back to heuristic
		// (Last-Modified-based) caching, which can serve a stale landing page.
		c.Set("Cache-Control", "public, max-age=300, must-revalidate")
		return c.SendFile(indexHTML)
	})

	// Serve the standalone emoji memory game at /game
	app.Get("/game", func(c *fiber.Ctx) error {
		if _, err := os.Stat(gameHTML); err != nil {
			return fiber.NewError(fiber.StatusNotFound, "game not found")
		}
		c.Set("Cache-Control", "public, max-age=300, must-revalidate")
		return c.SendFile(gameHTML)
	})

	// Serve vendored front-end modules (three.js) at /vendor/* — self-hosted so
	// the 3D landing has no runtime CDN dependency. ES modules MUST be served with
	// a JavaScript MIME type or the browser refuses to execute them.
	app.Get("/vendor/*", func(c *fiber.Ctx) error {
		filePath := c.Params("*")
		if filePath == "" {
			return fiber.NewError(fiber.StatusBadRequest, "file path required")
		}
		cleanPath, ok := resolveUnder(vendorDir, filePath)
		if !ok {
			return fiber.NewError(fiber.StatusForbidden, "access denied")
		}
		if _, err := os.Stat(cleanPath); err != nil {
			return fiber.NewError(fiber.StatusNotFound, "vendor file not found: "+filePath)
		}
		switch filepath.Ext(cleanPath) {
		case ".js", ".mjs":
			c.Set("Content-Type", "text/javascript; charset=utf-8")
		case ".map", ".json":
			c.Set("Content-Type", "application/json; charset=utf-8")
		case ".css":
			c.Set("Content-Type", "text/css; charset=utf-8")
		}
		// Versioned, immutable vendored assets: cache hard.
		c.Set("Cache-Control", "public, max-age=31536000, immutable")
		return c.SendFile(cleanPath)
	})

	// List available distributions
	app.Get("/files", func(c *fiber.Ctx) error {
		files := make([]fiber.Map, 0)

		// Walk distr directory
		err := filepath.Walk(distrDir, func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return nil // Skip errors
			}
			if info.IsDir() {
				return nil
			}

			relPath, _ := filepath.Rel(distrDir, path)
			files = append(files, fiber.Map{
				"name":     relPath,
				"size":     info.Size(),
				"modified": info.ModTime(),
				"url":      "/distr/" + relPath,
			})
			return nil
		})
		if err != nil {
			log.Printf("Error listing files: %v", err)
		}

		return c.JSON(fiber.Map{
			"version": version,
			"files":   files,
			"count":   len(files),
		})
	})

	// Serve EGE materials at clean route URLs (no .html extension).
	//   /ege               → ege/index.html
	//   /ege/<name>        → ege/<name>.html  (e.g. /ege/stereometria → ege/stereometria.html)
	serveEge := func(c *fiber.Ctx, name string) error {
		if name == "" {
			name = "index"
		}
		cleanPath, ok := resolveUnder(egeDir, name+".html")
		if !ok {
			return fiber.NewError(fiber.StatusForbidden, "access denied")
		}
		if _, err := os.Stat(cleanPath); err != nil {
			return fiber.NewError(fiber.StatusNotFound, "ege page not found: "+name)
		}
		// SendFile auto-sets Last-Modified + handles If-Modified-Since (304).
		c.Set("Cache-Control", "public, max-age=300, must-revalidate")
		return c.SendFile(cleanPath)
	}
	app.Get("/ege", func(c *fiber.Ctx) error {
		return serveEge(c, "")
	})
	app.Get("/ege/:name", func(c *fiber.Ctx) error {
		return serveEge(c, c.Params("name"))
	})

	// Serve EDU materials at clean route URLs (no .html extension).
	//   /edu            → edu/finances.html  (canonical course landing)
	//   /edu/finances   → edu/finances.html
	//   /edu/<name>     → edu/<name>.html
	serveEdu := func(c *fiber.Ctx, name string) error {
		if name == "" {
			name = "finances"
		}
		cleanPath, ok := resolveUnder(eduDir, name+".html")
		if !ok {
			return fiber.NewError(fiber.StatusForbidden, "access denied")
		}
		if _, err := os.Stat(cleanPath); err != nil {
			return fiber.NewError(fiber.StatusNotFound, "edu page not found: "+name)
		}
		c.Set("Cache-Control", "public, max-age=300, must-revalidate")
		return c.SendFile(cleanPath)
	}
	app.Get("/edu", func(c *fiber.Ctx) error {
		return serveEdu(c, "")
	})
	app.Get("/edu/:name", func(c *fiber.Ctx) error {
		return serveEdu(c, c.Params("name"))
	})

	// Serve SCHOOL materials at clean route URLs (no .html extension).
	//   /school          → school/index.html
	//   /school/<name>   → school/<name>.html  (e.g. /school/sharygin-pokolenia)
	serveSchool := func(c *fiber.Ctx, name string) error {
		if name == "" {
			name = "index"
		}
		cleanPath, ok := resolveUnder(schoolDir, name+".html")
		if !ok {
			return fiber.NewError(fiber.StatusForbidden, "access denied")
		}
		if _, err := os.Stat(cleanPath); err != nil {
			return fiber.NewError(fiber.StatusNotFound, "school page not found: "+name)
		}
		c.Set("Cache-Control", "public, max-age=300, must-revalidate")
		return c.SendFile(cleanPath)
	}
	app.Get("/school", func(c *fiber.Ctx) error {
		return serveSchool(c, "")
	})
	app.Get("/school/:name", func(c *fiber.Ctx) error {
		return serveSchool(c, c.Params("name"))
	})

	// Serve FUTURE materials at clean route URLs (no .html extension).
	//   /future          → future/index.html
	//   /future/<name>   → future/<name>.html  (e.g. /future/claude-code)
	serveFuture := func(c *fiber.Ctx, name string) error {
		if name == "" {
			name = "index"
		}
		cleanPath, ok := resolveUnder(futureDir, name+".html")
		if !ok {
			return fiber.NewError(fiber.StatusForbidden, "access denied")
		}
		if _, err := os.Stat(cleanPath); err != nil {
			return fiber.NewError(fiber.StatusNotFound, "future page not found: "+name)
		}
		c.Set("Cache-Control", "public, max-age=300, must-revalidate")
		return c.SendFile(cleanPath)
	}
	app.Get("/future", func(c *fiber.Ctx) error {
		return serveFuture(c, "")
	})
	app.Get("/future/:name", func(c *fiber.Ctx) error {
		return serveFuture(c, c.Params("name"))
	})

	// Serve the 3D orbital knowledge map at clean route URLs (no .html extension).
	//   /map          → map/index.html  (the three.js WebGL node-graph; linked from /)
	//   /map/<name>   → map/<name>.html
	serveMap := func(c *fiber.Ctx, name string) error {
		if name == "" {
			name = "index"
		}
		cleanPath, ok := resolveUnder(mapDir, name+".html")
		if !ok {
			return fiber.NewError(fiber.StatusForbidden, "access denied")
		}
		if _, err := os.Stat(cleanPath); err != nil {
			return fiber.NewError(fiber.StatusNotFound, "map page not found: "+name)
		}
		c.Set("Cache-Control", "public, max-age=300, must-revalidate")
		return c.SendFile(cleanPath)
	}
	app.Get("/map", func(c *fiber.Ctx) error {
		return serveMap(c, "")
	})
	app.Get("/map/:name", func(c *fiber.Ctx) error {
		return serveMap(c, c.Params("name"))
	})

	// Serve the Elixir course as a folder tree. This section is FOLDER-routed
	// (multi-segment) — unlike the flat <name>.html sections above — so it uses a
	// wildcard route and a try_files-style cascade on the path under elixirDir:
	//   /elixir                         → elixir/index.html                    (dir → its index.html)
	//   /elixir/algebra                 → elixir/algebra/index.html            (dir → its index.html)
	//   /elixir/algebra/f1-01-functions → elixir/algebra/f1-01-functions.html  (clean leaf URL → .html)
	//   /elixir/algebra/diagram.svg     → elixir/algebra/diagram.svg           (exact co-located file)
	// resolveUnder guards every join, so ".." in any segment is rejected (403) —
	// the same path-traversal guard the /distr/* and /vendor/* wildcards use.
	serveElixir := func(c *fiber.Ctx, sub string) error {
		cleanPath, ok := resolveUnder(elixirDir, strings.Trim(sub, "/"))
		if !ok {
			return fiber.NewError(fiber.StatusForbidden, "access denied")
		}
		info, err := os.Stat(cleanPath)
		switch {
		case err == nil && info.IsDir():
			// Directory → serve its index.html (pretty-URL folder landing).
			cleanPath = filepath.Join(cleanPath, "index.html")
			if st, e := os.Stat(cleanPath); e != nil || st.IsDir() {
				return fiber.NewError(fiber.StatusNotFound, "elixir page not found: "+sub)
			}
		case err != nil:
			// No exact match → try the clean-URL form (<path>.html). Appending a
			// fixed suffix to an already-guarded path keeps it under elixirDir.
			html := cleanPath + ".html"
			if st, e := os.Stat(html); e != nil || st.IsDir() {
				return fiber.NewError(fiber.StatusNotFound, "elixir page not found: "+sub)
			}
			cleanPath = html
		}
		// The remaining case (err == nil && !IsDir) is an exact file — e.g. an
		// explicit .html or a co-located .svg/.png — served as-is by SendFile,
		// which sets the Content-Type from the extension.
		c.Set("Cache-Control", "public, max-age=300, must-revalidate")
		return c.SendFile(cleanPath)
	}
	app.Get("/elixir", func(c *fiber.Ctx) error {
		return serveElixir(c, "")
	})
	app.Get("/elixir/*", func(c *fiber.Ctx) error {
		return serveElixir(c, c.Params("*"))
	})

	// Serve distribution files with proper headers
	app.Get("/distr/*", func(c *fiber.Ctx) error {
		filePath := c.Params("*")
		if filePath == "" {
			return fiber.NewError(fiber.StatusBadRequest, "file path required")
		}

		cleanPath, ok := resolveUnder(distrDir, filePath)
		if !ok {
			return fiber.NewError(fiber.StatusForbidden, "access denied")
		}

		// Check file exists
		info, err := os.Stat(cleanPath)
		if err != nil {
			return fiber.NewError(fiber.StatusNotFound, "file not found: "+filePath)
		}

		// Set headers
		c.Set("Content-Type", "application/gzip")
		c.Set("Content-Length", strconv.FormatInt(info.Size(), 10))
		c.Set("Content-Disposition", fmt.Sprintf("attachment; filename=%q", filepath.Base(filePath)))
		c.Set("Cache-Control", "public, max-age=31536000, immutable") // 1 year cache

		return c.SendFile(cleanPath)
	})

	log.Printf("Starting jonnify v%s on port %s, distr: %s, index: %s, ege: %s, edu: %s, school: %s, future: %s, map: %s, elixir: %s, game: %s, health: %s, error: %s (%d pages)", version, port, distrDir, indexHTML, egeDir, eduDir, schoolDir, futureDir, mapDir, elixirDir, gameHTML, healthHTML, errorDir, len(errorPages))
	log.Fatal(app.Listen(":" + port))
}

// loadErrorPages reads every <status>.html in dir (e.g. 404.html, 503.html) into
// memory, keyed by status code. Only filenames that parse to an HTTP error code
// (400–599) are loaded, so dropping a new NNN.html into the dir is enough to add
// a page — no code change needed. Missing/unreadable files are skipped silently;
// the renderer falls back to JSON for any code without a page.
func loadErrorPages(dir string) map[int][]byte {
	pages := make(map[int][]byte)
	matches, _ := filepath.Glob(filepath.Join(dir, "*.html"))
	for _, p := range matches {
		code, err := strconv.Atoi(strings.TrimSuffix(filepath.Base(p), ".html"))
		if err != nil || code < 400 || code > 599 {
			continue
		}
		if body, readErr := os.ReadFile(p); readErr == nil {
			pages[code] = body
		}
	}
	return pages
}

// renderError writes an error response for the given status code. Browsers (which
// send Accept: text/html) get the styled HTML page when one exists; API clients,
// curl, and health probes get a JSON body. SendFile is deliberately NOT used —
// it would reset the status to 200 — so the cached bytes are written with Send,
// preserving the real error status.
func renderError(c *fiber.Ctx, code int, msg string) error {
	if body, ok := errorPages[code]; ok &&
		c.Accepts(fiber.MIMEApplicationJSON, fiber.MIMETextHTML) == fiber.MIMETextHTML {
		c.Set(fiber.HeaderCacheControl, "no-store")
		return c.Status(code).Type("html", "utf-8").Send(body)
	}
	return c.Status(code).JSON(fiber.Map{"error": msg})
}

// resolveUnder joins name onto dir and returns the cleaned path, with ok=false
// when the result escapes dir (the path-traversal guard). Unlike a raw string
// prefix test it (a) cleans dir too, so it works with relative dirs such as
// "./ege" where filepath.Join+Clean drop the leading "./", and (b) requires a
// path separator right after dir, so a sibling like "/app/egevil" cannot pass as
// being under "/app/ege".
func resolveUnder(dir, name string) (string, bool) {
	cleanDir := filepath.Clean(dir)
	cleanPath := filepath.Clean(filepath.Join(cleanDir, name))
	if cleanPath != cleanDir && !strings.HasPrefix(cleanPath, cleanDir+string(os.PathSeparator)) {
		return "", false
	}
	return cleanPath, true
}
