packages:
  - "packages/*"
  - "apps/*"
  - "codemojex/packages/*"
  - "codemojex/apps/*"

catalog:
  typescript: ~5.9.3
  vite: ^7
  vitest: ^4
  react: ^19
  react-dom: ^19
  jsdom: ^26
  "@vitejs/plugin-react": ^4.3.3
