# fly.toml app configuration file generated for echo-postgres on 2026-06-25T15:36:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'echo-postgres'
primary_region = 'fra'
kill_signal = 'SIGINT'
kill_timeout = '1m0s'

[build]
  dockerfile = 'Dockerfile'

[env]
  POSTGRES_DB = 'codemojex'

[[mounts]]
  source = 'pg_data'
  destination = '/var/lib/postgresql/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.alive]
    port = 5432
    type = 'tcp'
    interval = '15s'
    timeout = '2s'
    grace_period = '30s'

[[vm]]
  size = 'shared-cpu-2x'
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048
