// @codemoji/design — "sort out": turn the raw extraction into organized,
// human- and agent-readable artifacts (manifest + figure-by-figure spec +
// token map). Maps Figma values onto the codemoji-app src/styles.css tokens.

// Known codemoji-app design tokens (node/codemoji-app/src/styles.css), so the
// generated token map can flag exact matches vs new/unmapped colors.
const KNOWN_COLORS = [
  ['#FF8400', '--color-accent (orange)'],
  ['#FF2F00', '--color-accent-secondary'],
  ['#00D95F', '--color-success'],
  ['#333333', '--color-dark-muted / --foreground'],
  ['#666666', '--color-muted'],
  ['#FFFFFF', '--card / --primary-foreground'],
  ['#000000', '--primary'],
  ['#E8F3F7', '--color-bg-from / --color-bg-main'],
  ['#E9F3F7', '--color-bg-from (≈)'],
  ['#AFC7D6', '--color-bg-to / --color-bg-secondary'],
  ['#D8E4EB', '--background'],
  ['#0050FF', '--link'],
  ['#E8EFF1', '--slot / --drawer'],
  ['#A6DEF5', '--slot-active'],
];
const TEXT_SCALE = { 26: '--text-large', 20: '--text-h1', 18: '--text-h2', 16: '--text-h3', 14: '--text-h4', 12: '--text-h5', 10: '--text-h6 / --text-2xs' };

// The figma-local MCP improvement backlog — every gap the toolkit hits on the
// LIVE primitives, with the fork that fixes it. Embedded in every manifest so
// the extraction output itself carries the spec rationale.
export const GAPS = [
  { id: 'egress', problem: 'export-node returns {data:[int...]} (~6-10x bytes; ~1M tokens for a screen)', fix: 'plugin figma.base64Encode + Mac-side file write -> {path,w,h,byteLen}', fork: '2 / B1' },
  { id: 'tree', problem: 'no recursive subtree fetch; ~1 get-node-properties call per node', fix: 'get-node-tree over exportAsync({format:JSON_REST_V1}) + depth/fields/maxNodes', fork: '3 / C1' },
  { id: 'props', problem: 'get-node-properties omits cornerRadius, auto-layout, absoluteBoundingBox, full typography', fix: 'enrich serializeNodeDetailed (+ figma.mixed guard, getStyledTextSegments)', fork: '1 / A1' },
  { id: 'tokens', problem: 'fills carry raw VariableID aliases, unresolved', fix: 'resolve-variables via Variable.resolveForConsumer (plugin-only; consumer cannot)', fork: '4 / D1' },
  { id: 'instances', problem: '~150 repeated emoji tiles not deduped; no component info in payload', fix: 'get-component-instances via getMainComponentAsync + overrides', fork: '4 / D1' },
  { id: 'dead-tools', problem: 'get-batch-nodes / export-batch-nodes advertised in mcp.js but unimplemented in plugin', fix: 'implement handlers or drop registrations (advertised == live)', fork: '1 / stabilize' },
];

const norm = (h) => (h || '').toLowerCase().slice(0, 7);
const matchToken = (h) => { const m = KNOWN_COLORS.find(([k]) => norm(k) === norm(h)); return m ? m[1] : null; };

/** Figures = visible, non-trivial depth 1-2 nodes, ordered top-to-bottom. */
export function figuresOf(nodes, renders) {
  return nodes
    .filter((n) => !n.error && n.depth >= 1 && n.depth <= 2 && n.visible !== false && (n.w || 0) >= 40 && (n.h || 0) >= 24)
    .sort((a, b) => (a.y || 0) - (b.y || 0))
    .map((n) => ({ id: n.id, name: n.name, type: n.type, x: n.x, y: n.y, w: n.w, h: n.h, childCount: n.childCount, render: renders.find((r) => r.id === n.id && !r.error)?.file || null }));
}

export function buildManifest({ screen, nodes, renders, imageAssets, source, stamp }) {
  const figures = figuresOf(nodes, renders);
  return {
    tool: '@codemoji/design extract',
    screen, source, generatedAt: stamp || null,
    counts: { nodes: nodes.length, figures: figures.length, renders: renders.filter((r) => !r.error).length, imageAssets: imageAssets.length },
    figures,
    gaps: GAPS,
  };
}

export function specMarkdown(manifest, nodes) {
  const byId = new Map(nodes.map((n) => [n.id, n]));
  const L = [];
  L.push(`# ${manifest.screen.name} — design spec (extracted)`, '');
  L.push(`> Generated by \`@codemoji/design extract\` from ${manifest.source}. Figures ordered top-to-bottom.`, '');
  L.push(`Screen \`${manifest.screen.id}\` · ${manifest.counts.figures} figures · ${manifest.counts.nodes} nodes walked · ${manifest.counts.renders} renders.`, '');
  L.push('> Reconstruction note: cornerRadius, auto-layout spacing/padding and resolved token values are NOT in the current payload (see `gaps` in manifest.json) — read them from the reference PNG until the MCP enhancement lands.', '');
  L.push('> Figure → React-slice mapping lives in the app guide [node/codemoji-app/CLAUDE.md](../../../codemoji-app/CLAUDE.md), not here: this spec is the raw extraction (what each figure *is*); the app guide owns where each figure is *built*.', '');
  for (const [i, f] of manifest.figures.entries()) {
    const n = byId.get(f.id) || {};
    L.push(`## ${String(i + 1).padStart(2, '0')}. ${f.name}  \`${f.type}\``);
    L.push(`- id \`${f.id}\` · ${Math.round(f.w)}×${Math.round(f.h)} @ (${Math.round(f.x)}, ${Math.round(f.y)}) · ${f.childCount} children`);
    if (f.render) L.push(`- render: [\`reference/${f.render}\`](reference/${f.render})`);
    if (n.fills) L.push(`- fills: ${n.fills.map((x) => x.t === 'SOLID' ? (x.hex + (x.var ? ` (var ${x.var} — UNRESOLVED)` : '')) : x.t === 'IMAGE' ? `IMAGE(${x.hash?.slice(0, 8)}…)` : `${x.t}[${(x.stops || []).join('→')}]`).join(', ')}`);
    if (n.text) L.push(`- text: "${(n.text.chars || '').slice(0, 48)}" · ${n.text.font?.family || '?'} ${n.text.font?.style || ''} ${n.text.fontSize}px`);
    if (n.effects) L.push(`- effects: ${n.effects.map((e) => `${e.t} r${e.radius}`).join(', ')}`);
    L.push('');
  }
  return L.join('\n') + '\n';
}

export function tokensMarkdown(nodes) {
  const colors = new Map(); // hex -> count
  const fonts = new Map();  // "family|style|size" -> count
  let unresolvedVars = 0;
  for (const n of nodes) {
    for (const f of n.fills || []) {
      if (f.hex) colors.set(f.hex, (colors.get(f.hex) || 0) + 1);
      if (f.var) unresolvedVars++;
      for (const s of f.stops || []) if (s) colors.set(s, (colors.get(s) || 0) + 1);
    }
    for (const s of n.strokes || []) if (s.hex) colors.set(s.hex, (colors.get(s.hex) || 0) + 1);
    if (n.text) { const k = `${n.text.font?.family || '?'}|${n.text.font?.style || ''}|${n.text.fontSize}`; fonts.set(k, (fonts.get(k) || 0) + 1); }
  }
  const L = ['# Tokens — Figma → codemoji-app (src/styles.css)', ''];
  L.push('## Colors', '', '| Figma | uses | styles.css token |', '|---|---|---|');
  for (const [h, c] of [...colors.entries()].sort((a, b) => b[1] - a[1])) L.push(`| \`${h}\` | ${c} | ${matchToken(h) || '— (new/unmapped)'} |`);
  L.push('', '## Typography', '', '| family | style | px | uses | scale |', '|---|---|---|---|---|');
  for (const [k, c] of [...fonts.entries()].sort((a, b) => b[1] - a[1])) { const [fam, st, sz] = k.split('|'); L.push(`| ${fam} | ${st} | ${sz} | ${c} | ${TEXT_SCALE[sz] || '—'} |`); }
  if (unresolvedVars) L.push('', `> ${unresolvedVars} fill(s) are bound to Figma variables whose values are UNRESOLVED — needs the \`resolve-variables\` MCP tool (Fork 4 / D1). The hex above is the baked value, not the token binding.`);
  return L.join('\n') + '\n';
}
