s3:
  endpoint: https://fly.storage.tigris.dev
  region: auto
  access_key: tid_COonCrlRDivvOiaHWIXRvUOaMQ_ZeORBQTRwHpxKAdkmxniQWH
  api_key: tsec_-TBK74QYNMdFrDleu7tfJp7FeYwdlfkFkMSpWia1FgMRdw0gnDoI8Rye2R_6keQ0G_Jpcz
  bucket: codemoji-packages
  prefix: ""
  restore_days: 7
  enable_glacier_restore: false
  skip_bucket_validation: false
  enable_upload: false
  enable_delete: false

database:
  url: "postgres://jonny@localhost:5432/s3xplorer?sslmode=disable"

scan:
  enable_background_scan: false
  cron_schedule: "0 2 * * *"
  enable_initial_scan: true
  enable_deletion_sync: false

log_level: info
