// litestream/generate.go
// =============================================================================
// DYNAMIC LITESTREAM.YML GENERATOR
// =============================================================================
//
// Generates litestream.yml configuration dynamically from flyer config.
// Applies Phase 5 learnings:
//   - L-14: Litestream config is static YAML — must regenerate on changes
//   - L-15: Process env inheritance — use ${VAR} placeholders, not resolved values
//   - L-16: Supports multiple databases for batch config generation
//
// Usage:
//   flyer stream generate                       # Generate from flyer.conf
//   flyer stream generate --output /tmp/ls.yml  # Custom output path
//
// =============================================================================

package litestream

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"text/template"
	"time"
)

// DatabaseEntry represents a single database to replicate
type DatabaseEntry struct {
	// Path to the SQLite database file
	Path string

	// S3Path is the prefix path within the S3 bucket for this database's replica
	S3Path string
}

// GenerateConfig holds all parameters for YAML generation
type GenerateConfig struct {
	// S3 configuration
	Endpoint string
	Bucket   string
	Region   string

	// Replication settings
	SyncInterval           string
	SnapshotInterval       string
	Retention              string
	RetentionCheckInterval string
	ValidationInterval     string

	// Databases to replicate
	Databases []DatabaseEntry
}

// DefaultSyncInterval is optimized for deployment state (changes slowly)
const DefaultSyncInterval = "10s"

// DefaultSnapshotInterval for periodic full snapshots
const DefaultSnapshotInterval = "1h"

// DefaultRetention keeps 72 hours of WAL history
const DefaultRetention = "72h"

// DefaultRetentionCheckInterval for retention cleanup
const DefaultRetentionCheckInterval = "1h"

// DefaultValidationInterval for integrity verification
const DefaultValidationInterval = "1h"

// litestreamTemplate is the Go text/template for litestream.yml
// Uses ${VAR} env references (D-4: Litestream resolves from process env per L-15)
const litestreamTemplate = `# litestream.yml — Generated by flyer stream generate
# ============================================================================
# Generated: {{ .Timestamp }}
# Databases: {{ len .Config.Databases }}
# Bucket: {{ .Config.Bucket }}
# ============================================================================

# Tigris S3 credentials (resolved from process environment by Litestream)
access-key-id: ${AWS_ACCESS_KEY_ID}
secret-access-key: ${AWS_SECRET_ACCESS_KEY}

# Database configurations
dbs:
{{- range .Config.Databases }}
  - path: {{ .Path }}
    replicas:
      - type: s3
        bucket: {{ $.Config.Bucket }}
        path: {{ .S3Path }}
        endpoint: {{ $.Config.Endpoint }}
        region: {{ $.Config.Region }}
        sync-interval: {{ $.Config.SyncInterval }}
        snapshot-interval: {{ $.Config.SnapshotInterval }}
        retention: {{ $.Config.Retention }}
        retention-check-interval: {{ $.Config.RetentionCheckInterval }}
        validation-interval: {{ $.Config.ValidationInterval }}
{{- end }}
`

// templateData is the context passed to the template
type templateData struct {
	Config    *GenerateConfig
	Timestamp string
}

// Generate produces litestream.yml content from the given config
func Generate(cfg *GenerateConfig) ([]byte, error) {
	if len(cfg.Databases) == 0 {
		return nil, fmt.Errorf("no databases configured for replication")
	}

	// Apply defaults for any empty settings
	applyDefaults(cfg)

	tmpl, err := template.New("litestream").Parse(litestreamTemplate)
	if err != nil {
		return nil, fmt.Errorf("parse template: %w", err)
	}

	data := templateData{
		Config:    cfg,
		Timestamp: time.Now().UTC().Format(time.RFC3339),
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("execute template: %w", err)
	}

	return buf.Bytes(), nil
}

// GenerateToFile generates litestream.yml and writes it to the specified path
func GenerateToFile(cfg *GenerateConfig, outputPath string) error {
	content, err := Generate(cfg)
	if err != nil {
		return err
	}

	// Ensure parent directory exists
	dir := filepath.Dir(outputPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create directory %s: %w", dir, err)
	}

	if err := os.WriteFile(outputPath, content, 0644); err != nil {
		return fmt.Errorf("write %s: %w", outputPath, err)
	}

	return nil
}

func applyDefaults(cfg *GenerateConfig) {
	if cfg.SyncInterval == "" {
		cfg.SyncInterval = DefaultSyncInterval
	}
	if cfg.SnapshotInterval == "" {
		cfg.SnapshotInterval = DefaultSnapshotInterval
	}
	if cfg.Retention == "" {
		cfg.Retention = DefaultRetention
	}
	if cfg.RetentionCheckInterval == "" {
		cfg.RetentionCheckInterval = DefaultRetentionCheckInterval
	}
	if cfg.ValidationInterval == "" {
		cfg.ValidationInterval = DefaultValidationInterval
	}
	if cfg.Region == "" {
		cfg.Region = "auto"
	}
	if cfg.Endpoint == "" {
		cfg.Endpoint = "https://fly.storage.tigris.dev"
	}

	// Default S3 paths from database filenames
	for i := range cfg.Databases {
		if cfg.Databases[i].S3Path == "" {
			base := filepath.Base(cfg.Databases[i].Path)
			ext := filepath.Ext(base)
			name := base[:len(base)-len(ext)]
			cfg.Databases[i].S3Path = "db/" + name
		}
	}
}
