defmodule Portal.FacadeTest do
  @moduledoc """
  The `Portal` facade (F6.4-D4/INV2): a thin module that exposes each public function
  and routes it to its context, owning no logic. Asserts the facade's public surface
  exists at the expected arities and that representative calls return byte-identical
  results to the context they delegate to (behavioural defdelegate parity).

  async: false + Portal.DataCase shared sandbox — the enrollment reads route through
  the named Portal.Engine, whose course-exists gate reads Repo inside that process.
  """
  use Portal.DataCase, async: false

  alias Portal.Catalog

  setup do
    Portal.Store.reset()
    Portal.EventStore.InMemory.reset()
    Portal.Engine.reset()

    on_exit(fn ->
      Portal.Store.reset()
      Portal.EventStore.InMemory.reset()
      Portal.Engine.reset()
    end)

    :ok
  end

  test "the facade exposes the pinned public surface at the right arities" do
    exported = Portal.__info__(:functions)

    for {name, arity} <- [
          # Enrollment
          enroll: 2,
          deliver_lesson: 2,
          courses_of: 1,
          progress_of: 1,
          enroll_and_welcome: 2,
          # Catalog
          list_courses: 0,
          get_course!: 1,
          fetch_course: 1,
          create_course: 1,
          lesson: 1,
          # Accounts
          user: 1,
          welcome: 1
        ] do
      assert {name, arity} in exported,
             "Portal facade is missing #{name}/#{arity}"
    end
  end

  test "Portal.fetch_course/1 returns the same as Portal.Catalog.fetch_course/1 (defdelegate parity)" do
    {:ok, course} = Catalog.create_course(%{title: "Parity", slug: "parity"})

    assert Portal.fetch_course(course.id) == Catalog.fetch_course(course.id)
    assert Portal.fetch_course(Portal.ID.new("CRS")) == {:error, :not_found}
  end

  test "Portal.courses_of/1 returns the same wrapped list as Portal.Enrollment.courses_of/1" do
    user_id = Portal.ID.new("USR")
    assert Portal.courses_of(user_id) == Portal.Enrollment.courses_of(user_id)
    assert {:ok, []} = Portal.courses_of(user_id)
  end

  test "the facade owns no logic: every public function body is a bare defdelegate" do
    # Each public Portal function is generated by `defdelegate`, so its compiled body is
    # a single delegating call — no `case`/`with`/`cond` AST node appears (INV2). Verify
    # structurally from the function defs in the source, excluding the @moduledoc (whose
    # consumer sketch legitimately shows a `case`).
    source = File.read!(Path.join([__DIR__, "..", "..", "lib", "portal.ex"]))
    [_doc, defs] = String.split(source, ~r/^  defdelegate/m, parts: 2)
    defs = "  defdelegate" <> defs

    # The only function-defining construct below the moduledoc is `defdelegate` — no
    # `def ` with a `do` body, and no control-flow keyword.
    refute defs =~ ~r/^\s*def /m
    refute defs =~ ~r/\bcase\b/
    refute defs =~ ~r/\bwith\b/
    refute defs =~ ~r/\bcond\b/
  end
end
