defmodule Portal.FacadeTest do
  @moduledoc """
  The `Portal` facade (F6.4-D4/INV2): a thin module that exposes each public function
  and routes it to its context, owning no logic. Asserts the facade's public surface
  exists at the expected arities and that representative calls return byte-identical
  results to the context they delegate to (behavioural defdelegate parity).

  async: false + Portal.DataCase shared sandbox — the enrollment reads route through
  the named Portal.Engine, whose course-exists gate reads Repo inside that process.
  """
  use Portal.DataCase, async: false

  alias Portal.Catalog

  setup do
    Portal.Store.reset()
    Portal.EventStore.InMemory.reset()
    Portal.Engine.reset()

    on_exit(fn ->
      Portal.Store.reset()
      Portal.EventStore.InMemory.reset()
      Portal.Engine.reset()
    end)

    :ok
  end

  test "the facade exposes the pinned public surface at the right arities" do
    exported = Portal.__info__(:functions)

    for {name, arity} <- [
          # Enrollment
          enroll: 2,
          deliver_lesson: 2,
          courses_of: 1,
          progress_of: 1,
          enroll_and_welcome: 2,
          # Catalog
          list_courses: 0,
          get_course!: 1,
          fetch_course: 1,
          create_course: 1,
          update_course: 2,
          lesson: 1,
          # Accounts
          user: 1,
          welcome: 1,
          # Real-time (F6.7-D1)
          subscribe: 1,
          broadcast: 2
        ] do
      assert {name, arity} in exported,
             "Portal facade is missing #{name}/#{arity}"
    end
  end

  test "Portal.fetch_course/1 returns the same as Portal.Catalog.fetch_course/1 (defdelegate parity)" do
    {:ok, course} = Catalog.create_course(%{title: "Parity", slug: "parity"})

    assert Portal.fetch_course(course.id) == Catalog.fetch_course(course.id)
    assert Portal.fetch_course(Portal.ID.new("CRS")) == {:error, :not_found}
  end

  test "Portal.courses_of/1 returns the same wrapped list as Portal.Enrollment.courses_of/1" do
    user_id = Portal.ID.new("USR")
    assert Portal.courses_of(user_id) == Portal.Enrollment.courses_of(user_id)
    assert {:ok, []} = Portal.courses_of(user_id)
  end

  test "the facade owns no logic: every delegated function body is a bare defdelegate" do
    # Each delegated Portal function is generated by `defdelegate`, so its compiled body
    # is a single delegating call — no `case`/`with`/`cond` AST node appears (INV2).
    # Verify structurally from the function defs in the source, excluding the @moduledoc
    # (whose consumer sketch legitimately shows a `case`) AND the F6.7 real-time section
    # (the `subscribe`/`broadcast` PubSub wrappers, asserted separately below — they wrap
    # `Phoenix.PubSub` directly, so they cannot be `defdelegate`s, but they still own no
    # logic).
    source = File.read!(Path.join([__DIR__, "..", "..", "lib", "portal.ex"]))
    [_doc, after_doc] = String.split(source, ~r/^  defdelegate/m, parts: 2)
    # Scope the structural guard to the delegating block — up to the real-time section
    # marker — so the two D1 wrappers (the only non-defdelegate functions) are excluded.
    [delegates | _] = String.split("  defdelegate" <> after_doc, "# ── Real-time")

    # The only function-defining construct in the delegating block is `defdelegate` — no
    # `def ` with a `do` body, and no control-flow keyword.
    refute delegates =~ ~r/^\s*def /m
    refute delegates =~ ~r/\bcase\b/
    refute delegates =~ ~r/\bwith\b/
    refute delegates =~ ~r/\bcond\b/
  end

  test "the F6.7 real-time wrappers are single-expression pass-throughs over Portal.PubSub" do
    # `subscribe/1` and `broadcast/2` are the one exception to the bare-defdelegate idiom
    # (F6.7-D1): they wrap `Phoenix.PubSub` directly (no `Portal.*` target to delegate to).
    # They still own NO logic — one delegating call each, no control flow — so the master
    # invariant (INV2) holds: the wrappers are the facade's real-time boundary, naming the
    # transport ONCE so the web never does.
    source = File.read!(Path.join([__DIR__, "..", "..", "lib", "portal.ex"]))
    [_before, realtime] = String.split(source, "# ── Real-time", parts: 2)

    # Both wrappers are present, each a single pass-through to the named PubSub server.
    assert realtime =~ "def subscribe(topic), do: Phoenix.PubSub.subscribe(Portal.PubSub, topic)"

    assert realtime =~
             "def broadcast(topic, message), do: Phoenix.PubSub.broadcast(Portal.PubSub, topic, message)"

    # No control flow in the real-time section either — they are pass-throughs, not logic.
    refute realtime =~ ~r/\bcase\b/
    refute realtime =~ ~r/\bwith\b/
    refute realtime =~ ~r/\bcond\b/
  end
end
