defmodule Mix.Tasks.Codemojex.Stories do
  @shortdoc "Generate the BDD acceptance-criteria catalogue from the codemojex story tests"

  @moduledoc """
  Generate the **features-delivered catalogue** from the self-documenting BDD story
  tests (`test/stories/*_story_test.exs`, written with `Codemojex.Story`).

      mix codemojex.stories            # writes docs/codemojex/stories/<feature>.stories.md + README.md
      mix codemojex.stories --out DIR  # write somewhere else
      mix codemojex.stories --match scoring   # only files whose name contains "scoring"

  Each story module's `feature`/`scenario`/`given_`/`when_`/`then_` source is BOTH a
  runnable ExUnit acceptance test (pure scenarios run anywhere; integration ones run
  under `mix test --include valkey` against Postgres + Valkey) AND the source of its
  story. This task reads the **compile-time** registry (`__stories__/0`) — it never
  runs the suite, so it needs no database or Valkey: a scenario reaches the catalogue
  only because a test that drives the real Codemojex surface compiled.

  Re-run after adding or editing a story scenario so the catalogue stays as-built.
  """

  use Mix.Task

  @app_dir Path.expand("../../..", __DIR__)
  @repo_root Path.expand("../../../../../..", __DIR__)
  @default_out Path.join(@repo_root, "docs/codemojex/stories")
  @stories_glob Path.join(@app_dir, "test/stories/*_story_test.exs")
  @dsl_file Path.join(@app_dir, "test/support/codemojex/story.ex")

  @step_labels %{given_: "Given", when_: "When", then_: "Then", and_: "And", but_: "But"}

  @impl Mix.Task
  def run(argv) do
    {opts, _rest, _invalid} = OptionParser.parse(argv, strict: [out: :string, match: :string])
    out_dir = opts[:out] || @default_out
    match = opts[:match]

    Mix.Task.run("compile")

    {:ok, _} = Application.ensure_all_started(:ex_unit)
    ExUnit.start(autorun: false)

    ensure_dsl_loaded()

    stories = load_stories(match)

    if stories == [] do
      Mix.shell().info("No story modules found under #{Path.relative_to_cwd(@stories_glob)} — nothing to generate.")
    else
      File.mkdir_p!(out_dir)
      Enum.each(stories, &write_feature(&1, out_dir))
      write_catalogue(stories, out_dir)

      total = stories |> Enum.map(&length(&1.scenarios)) |> Enum.sum()

      Mix.shell().info([
        :green,
        "Generated #{length(stories)} feature file(s) (#{total} scenarios) + README.md in ",
        :reset,
        Path.relative_to(out_dir, @repo_root)
      ])
    end
  end

  # -- loading ---------------------------------------------------------------

  defp ensure_dsl_loaded do
    unless Code.ensure_loaded?(Codemojex.Story), do: Code.require_file(@dsl_file)
  end

  defp load_stories(match) do
    @stories_glob
    |> Path.wildcard()
    |> Enum.filter(&matches?(&1, match))
    |> Enum.sort()
    |> Enum.flat_map(fn file ->
      (Code.require_file(file) || [])
      |> Enum.map(fn {mod, _bin} -> mod end)
      |> Enum.filter(&function_exported?(&1, :__stories__, 0))
      |> Enum.map(fn mod -> Map.put(mod.__stories__(), :file, file) end)
    end)
    |> Enum.sort_by(& &1.feature)
  end

  defp matches?(_file, nil), do: true
  defp matches?(file, substr), do: String.contains?(Path.basename(file), substr)

  # -- rendering -------------------------------------------------------------

  defp write_feature(%{feature: feature, slug: slug, scenarios: scenarios, file: file}, out_dir) do
    path = Path.join(out_dir, "#{slug}.stories.md")
    File.write!(path, render_feature(feature, scenarios, file))
  end

  defp render_feature(feature, scenarios, file) do
    count = length(scenarios)
    plural = if count == 1, do: "scenario", else: "scenarios"

    header = """
    <!-- GENERATED by `mix codemojex.stories` from #{Path.relative_to(file, @repo_root)} — do not edit by hand. -->

    # #{feature}

    > **Feature delivered — acceptance criteria.** Generated from the as-built BDD tests in
    > `#{Path.relative_to(file, @app_dir)}`. Every scenario below is an ExUnit test driving the
    > real Codemojex game, so the catalogue cannot drift from the code.

    **#{count} #{plural}.**
    """

    body = scenarios |> Enum.map(&render_scenario/1) |> Enum.join("\n")
    String.trim_trailing(header) <> "\n\n" <> body
  end

  defp render_scenario(%{title: title, steps: steps}) do
    lines =
      case steps do
        [] -> "_(no steps recorded)_"
        _ -> steps |> Enum.map(&render_step/1) |> Enum.join("\n")
      end

    "## Scenario: #{title}\n\n#{lines}\n"
  end

  defp render_step({kw, text}) do
    label = Map.fetch!(@step_labels, kw)
    "- **#{label}** #{text}"
  end

  defp write_catalogue(stories, out_dir) do
    rows =
      stories
      |> Enum.map(fn %{feature: f, slug: s, scenarios: sc} ->
        "| [#{f}](#{s}.stories.md) | #{length(sc)} |"
      end)
      |> Enum.join("\n")

    total = stories |> Enum.map(&length(&1.scenarios)) |> Enum.sum()

    catalogue = """
    <!-- GENERATED by `mix codemojex.stories` — do not edit by hand. -->

    # Codemojex — features delivered

    The acceptance-criteria catalogue, generated from the as-built BDD story tests
    under `test/stories/`. Each row is a feature whose Given/When/Then scenarios are
    runnable ExUnit tests against the real game.

    **#{length(stories)} features, #{total} scenarios.**

    | Feature | Scenarios |
    |---|---|
    #{rows}
    """

    File.write!(Path.join(out_dir, "README.md"), catalogue)
  end
end
