/**
 * TypeScript facade over the `echo-fx` wasm module.
 *
 * This is the seam the rest of Mercury imports — it keeps the wasm boundary
 * coarse-grained (one call per logical operation, no chatty per-field crossings)
 * and re-applies the branded types so callers carry the namespace through.
 *
 * Build the wasm first: `pnpm --filter @echo/fx build` (wasm-pack, target nodejs).
 * The import below resolves to the generated `pkg/`.
 */

// Generated by wasm-pack (target nodejs). Present after `pnpm fx:build`.
import * as wasm from "../pkg/echo_fx.js";

export type Namespace =
  | "PLR" | "ROM" | "GAM" | "GES" | "EMS" | "SES" | "JOB" | "TXN";

declare const NS: unique symbol;
export type BrandedId<N extends string> = string & { readonly [NS]: N };

export interface DecodedId<N extends string = string> {
  readonly namespace: N;
  readonly snowflake: bigint;
  readonly timestampMs: bigint;
  readonly node: number;
  readonly seq: number;
}

export function encode<N extends Namespace>(ns: N, snowflake: bigint): BrandedId<N> {
  return wasm.encode(ns, snowflake) as BrandedId<N>;
}

export function decode<N extends Namespace = Namespace>(id: string): DecodedId<N> {
  const d = wasm.decode(id);
  return {
    namespace: d.namespace as N,
    snowflake: d.snowflake,
    timestampMs: d.timestamp_ms,
    node: Number(d.node),
    seq: Number(d.seq),
  };
}

export function validate(id: string): boolean {
  return wasm.validate(id);
}

/** Routing hash. PARITY-pending vs EchoData.BrandedId.hash32/1. */
export function hash32(id: string): number {
  return wasm.hash32(id) >>> 0;
}

/**
 * A per-worker minter. Construct one per Node Cluster worker with a distinct
 * `node` id (0..1023) — that disjointness is what keeps ids unique across cores
 * without a shared lock.
 */
export class Minter {
  private readonly inner: wasm.Minter;
  constructor(node: number) {
    this.inner = new wasm.Minter(node);
  }
  snowflake(nowMs: number = Date.now()): bigint {
    return this.inner.mint_snowflake(nowMs);
  }
  mint<N extends Namespace>(ns: N, nowMs: number = Date.now()): BrandedId<N> {
    return this.inner.mint(ns, nowMs) as BrandedId<N>;
  }
}

/** Per-isolate loop-fusion primitive (demonstration). */
export function fusedSumOfSquares(values: Uint32Array, threshold: number): bigint {
  return wasm.fused_sum_of_squares(values, threshold);
}
