defmodule Mix.Tasks.EchoMq.Stories do
  @shortdoc "Generate the BDD acceptance-criteria catalogue from the echo_mq story tests"

  @moduledoc """
  Generate the **features-delivered catalogue** from the self-documenting BDD story
  tests (`test/stories/*_story_test.exs`, written with `EchoMQ.Story`).

      mix echo_mq.stories            # writes docs/echo_mq/stories/<feature>.stories.md + README.md
      mix echo_mq.stories --out DIR  # write somewhere else

  Each story module's `feature`/`scenario`/`given_`/`when_`/`then_` source is BOTH a
  runnable ExUnit acceptance test (proven against Valkey by `mix test --include valkey`)
  AND the source of its story. This task reads the **compile-time** registry
  (`__stories__/0`) — it never runs the suite, so it needs no Valkey connection: a
  scenario reaches the catalogue only because a test that drives the real EchoMQ surface
  compiled.

  Re-run after adding or editing a story scenario so the catalogue stays at as-built truth.
  """

  use Mix.Task

  # resolved at COMPILE time from this file's location, so the task is correct
  # regardless of the cwd it is invoked from (umbrella root or the app dir).
  @app_dir Path.expand("../../..", __DIR__)
  @repo_root Path.expand("../../../../../..", __DIR__)
  @default_out Path.join(@repo_root, "docs/echo_mq/stories")
  @stories_glob Path.join(@app_dir, "test/stories/*_story_test.exs")
  @dsl_file Path.join(@app_dir, "test/support/echo_mq/story.ex")

  @step_labels %{given_: "Given", when_: "When", then_: "Then", and_: "And", but_: "But"}

  @impl Mix.Task
  def run(argv) do
    {opts, _rest, _invalid} = OptionParser.parse(argv, strict: [out: :string, match: :string])
    out_dir = opts[:out] || @default_out
    match = opts[:match]

    # compile the app so EchoMQ.Flows / EchoMQ.Lanes / ... are loadable
    Mix.Task.run("compile")

    # ExUnit must be started before a module can `use ExUnit.Case` (the story
    # modules do, via `use EchoMQ.Story`); autorun: false so we never run them.
    {:ok, _} = Application.ensure_all_started(:ex_unit)
    ExUnit.start(autorun: false)

    ensure_dsl_loaded()

    stories = load_stories(match)

    if stories == [] do
      Mix.shell().info("No story modules found under #{Path.relative_to_cwd(@stories_glob)}#{match_note(match)} — nothing to generate.")
    else
      File.mkdir_p!(out_dir)
      Enum.each(stories, &write_feature(&1, out_dir))
      write_catalogue(stories, out_dir)

      total = stories |> Enum.map(&length(&1.scenarios)) |> Enum.sum()

      Mix.shell().info([
        :green,
        "Generated #{length(stories)} feature file(s) (#{total} scenarios) + README.md in ",
        :reset,
        Path.relative_to(out_dir, @repo_root)
      ])
    end
  end

  # -- loading ---------------------------------------------------------------

  defp ensure_dsl_loaded do
    unless Code.ensure_loaded?(EchoMQ.Story), do: Code.require_file(@dsl_file)
  end

  # Require each story file and pair every module that registered scenarios with
  # the file it came from (for the source link). Requiring compiles the module;
  # it does NOT run the tests, so no Valkey connection is opened.
  #
  # `match` (nil = all, the default) narrows the harvested FILE SET to story-test
  # files whose basename contains the substring — e.g. `--match wire_pipe` scopes
  # the output to the wire-pipe features, leaving the .stories.md / README format
  # byte-identical. With `match == nil` the set is unchanged from the bare glob.
  defp load_stories(match) do
    @stories_glob
    |> Path.wildcard()
    |> Enum.filter(&matches?(&1, match))
    |> Enum.sort()
    |> Enum.flat_map(fn file ->
      (Code.require_file(file) || [])
      |> Enum.map(fn {mod, _bin} -> mod end)
      |> Enum.filter(&function_exported?(&1, :__stories__, 0))
      |> Enum.map(fn mod -> Map.put(mod.__stories__(), :file, file) end)
    end)
    |> Enum.sort_by(& &1.feature)
  end

  defp matches?(_file, nil), do: true
  defp matches?(file, substr), do: String.contains?(Path.basename(file), substr)

  defp match_note(nil), do: ""
  defp match_note(substr), do: " matching #{inspect(substr)}"

  # -- rendering -------------------------------------------------------------

  defp write_feature(%{feature: feature, slug: slug, scenarios: scenarios, file: file}, out_dir) do
    path = Path.join(out_dir, "#{slug}.stories.md")
    File.write!(path, render_feature(feature, scenarios, file))
  end

  defp render_feature(feature, scenarios, file) do
    src_link = source_link(file)
    count = length(scenarios)
    plural = if count == 1, do: "scenario", else: "scenarios"

    header = """
    <!-- GENERATED by `mix echo_mq.stories` from #{Path.relative_to(file, @repo_root)} — do not edit by hand. -->

    # #{feature}

    > **Feature delivered — acceptance criteria.** Generated from the as-built BDD tests in
    > [`#{Path.relative_to(file, @app_dir)}`](#{src_link}). Every scenario below is a passing
    > ExUnit test driving the real `EchoMQ` surface against Valkey, so the catalogue cannot
    > drift from the code.

    **#{count} #{plural}.**
    """

    body = scenarios |> Enum.map(&render_scenario/1) |> Enum.join("\n")

    String.trim_trailing(header) <> "\n\n" <> body
  end

  defp render_scenario(%{title: title, steps: steps}) do
    lines =
      case steps do
        [] -> "_(no steps recorded)_"
        _ -> steps |> Enum.map(&render_step/1) |> Enum.join("\n")
      end

    "## Scenario: #{title}\n\n#{lines}\n"
  end

  defp render_step({keyword, text}) do
    label = Map.fetch!(@step_labels, keyword)
    "- **#{label}** #{text}"
  end

  defp write_catalogue(stories, out_dir) do
    rows =
      stories
      |> Enum.map(fn %{feature: f, slug: slug, scenarios: sc, file: file} ->
        "| [#{f}](#{slug}.stories.md) | #{length(sc)} | `#{Path.relative_to(file, @app_dir)}` |"
      end)
      |> Enum.join("\n")

    total = stories |> Enum.map(&length(&1.scenarios)) |> Enum.sum()

    content = """
    <!-- GENERATED by `mix echo_mq.stories` — do not edit by hand. -->

    # echo_mq — features delivered

    > A living catalogue of the bus's delivered features, as **acceptance criteria generated
    > from the as-built tests** (`test/stories/*_story_test.exs`) by `mix echo_mq.stories`.
    > Each feature's scenarios are passing BDD tests against the real EchoMQ surface on Valkey
    > — the catalogue is generated from code, never hand-written, so it cannot lie.

    | Feature | Scenarios | Source |
    |---|---|---|
    #{rows}

    _#{total} scenarios across #{length(stories)} feature(s). Regenerate with `mix echo_mq.stories`._
    """

    File.write!(Path.join(out_dir, "README.md"), content)
  end

  # link from docs/echo_mq/stories/<x>.stories.md back to the test source
  defp source_link(file), do: "../../../" <> Path.relative_to(file, @repo_root)
end
