defmodule EchoMQ.Stories.BatchFinishStoryTest do
  @moduledoc """
  Acceptance criteria for the **Batch finish** — the partitioned finish + dynamic
  delay (emq.5.4, the batches family CLOSER). The claim half (emq.5.1/5.2/5.3) gave
  a worker ways to CLAIM a batch; this closes the RESOLVE half. A claimed batch
  resolves as an EXHAUSTIVE, DISJOINT partition `%{completed, retried, dead,
  delayed}` over its members (the pure `EchoMQ.BatchFinish.partition/2`, `dead`
  EMERGING from the byte-frozen `@retry` `{:ok, :dead}` outcome, NOT a caller
  verdict). A handler that learns a member should run LATER (not fail) re-scores it
  with `EchoMQ.Jobs.delay/6` — an `active → scheduled` move that PRESERVES the
  member's attempts (the inverse of a claim: it releases the lease and mints
  nothing, one atomic `@delay` EVAL). The delay is TOKEN-FENCED (the
  `complete/5`/`retry/7` fencing): a stale lease-holder cannot re-delay a member
  another worker now owns.

  Written in the `EchoMQ.Story` BDD DSL: every scenario below is a real ExUnit
  test driving `EchoMQ.Jobs`/`EchoMQ.BatchFinish` against Valkey on 6390, AND the
  source of `docs/echo_mq/stories/batch-finish.stories.md` (generated by
  `mix echo_mq.stories`). The exhaustive wire coverage lives in the `:valkey`
  conformance scenarios (batch_partition / batch_delay / batch_delay_stale) and the
  pure partition coverage in `test/batch_finish_test.exs`.
  """
  use EchoMQ.Story, feature: "Batch finish", async: false

  @moduletag :valkey

  alias EchoData.BrandedId
  alias EchoMQ.{BatchFinish, Connector, Jobs, Keyspace}

  setup_all do
    :ok = EchoData.Snowflake.start(4)
    :ok
  end

  setup do
    {:ok, conn} = Connector.start_link(port: 6390)
    q = "emq.story.finish#{System.unique_integer([:positive])}"
    on_exit(fn -> purge(q) end)
    %{conn: conn, q: q}
  end

  scenario "a claimed batch resolves as an exhaustive, disjoint partition", %{conn: conn, q: q} do
    given_ "a claimed batch of four members, each headed to a different outcome" do
      [done, sched, dead, delayed] =
        ids =
        for _ <- 1..4 do
          id = BrandedId.generate!("JOB")
          {:ok, :enqueued} = Jobs.enqueue(conn, q, id, "p")
          id
        end

      {:ok, members} = Jobs.claim_batch(conn, q, 4, 60_000)
      tok = Map.new(members, fn {id, _p, att} -> {id, att} end)
    end

    when_ "each member is resolved through its real transition and the outcomes are partitioned" do
      # one completes, one retries (schedules, high cap), one retries PAST the cap
      # (cap 1 -> the {:ok, :dead} outcome EMERGES), one is delayed
      resolved = %{
        done => {:ok, Jobs.complete(conn, q, done, tok[done])},
        sched => {{:error, "boom"}, Jobs.retry(conn, q, sched, tok[sched], 5, 9, "boom")},
        dead => {{:error, "gave up"}, Jobs.retry(conn, q, dead, tok[dead], 5, 1, "gave up")},
        delayed => {{:delay, 30}, Jobs.delay(conn, q, delayed, tok[delayed], 30)}
      }

      part = BatchFinish.partition(ids, resolved)
    end

    then_ "the four buckets are a PERMUTATION of the claimed ids (exhaustive) and pairwise DISJOINT" do
      all = part.completed ++ part.retried ++ part.dead ++ part.delayed
      assert Enum.sort(all) == Enum.sort(ids)
      assert length(all) == length(Enum.uniq(all))
    end

    and_ "each member landed in its bucket, dead EMERGING from the retry outcome (not a caller verdict)" do
      assert part.completed == [done]
      assert part.retried == [sched]
      assert part.dead == [dead]
      assert part.delayed == [delayed]
    end

    but_ "a member ABSENT from the verdict map fail-safe-retries — unprocessed work is never reported completed" do
      # the same classifier, an absent member -> retried, never completed
      absent = BatchFinish.partition([done, "JOBabsent"], %{done => {:ok, :ok}})
      assert absent.completed == [done]
      assert absent.retried == ["JOBabsent"]
    end
  end

  scenario "a handler re-scores a member to run later, attempts preserved", %{conn: conn, q: q} do
    given_ "a claimed (active) member at attempts 1" do
      id = BrandedId.generate!("JOB")
      {:ok, :enqueued} = Jobs.enqueue(conn, q, id, "later")
      {:ok, {^id, _, 1}} = Jobs.claim(conn, q, 60_000)
    end

    when_ "the handler delays the member by 40ms (the relative, server-clock mode)" do
      result = Jobs.delay(conn, q, id, 1, 40)
    end

    then_ "the member moves to schedule with state scheduled and attempts STILL 1 (NOT reset — a delay is not a failure)" do
      assert :ok = result
      assert {:ok, "scheduled"} = Connector.command(conn, ["HGET", Keyspace.job_key(q, id), "state"])
      assert {:ok, "1"} = Connector.command(conn, ["HGET", Keyspace.job_key(q, id), "attempts"])
    end

    and_ "it is in the schedule set, ABSENT from active (the lease released), and invisible to claim until due" do
      assert {:ok, s} = Connector.command(conn, ["ZSCORE", Keyspace.queue_key(q, "schedule"), id])
      assert s != nil
      assert {:ok, nil} = Connector.command(conn, ["ZSCORE", Keyspace.queue_key(q, "active"), id])
      assert :empty == Jobs.claim(conn, q, 60_000)
    end

    and_ "once due, promote returns it to pending and a fresh claim mints attempts 2 (the history CONTINUED, not restarted)" do
      Process.sleep(60)
      assert {:ok, 1} = Jobs.promote(conn, q, 10)
      assert {:ok, {^id, "later", 2}} = Jobs.claim(conn, q, 60_000)
    end
  end

  scenario "only the current lease holder may delay a member", %{conn: conn, q: q} do
    given_ "a member claimed by worker A (token 1), then reaped and re-claimed by worker B (token 2)" do
      id = BrandedId.generate!("JOB")
      {:ok, :enqueued} = Jobs.enqueue(conn, q, id, "w")
      {:ok, {^id, _, 1}} = Jobs.claim(conn, q, 30)
      Process.sleep(60)
      {:ok, 1} = Jobs.reap(conn, q)
      {:ok, {^id, _, 2}} = Jobs.claim(conn, q, 60_000)
    end

    when_ "worker A delays with the now-stale token 1" do
      stale = Jobs.delay(conn, q, id, 1, 50)
    end

    then_ "the delay is refused EMQSTALE (-> {:error, :stale}) and worker B's token-2 lease is UNTOUCHED" do
      assert {:error, :stale} = stale
      assert {:ok, s} = Connector.command(conn, ["ZSCORE", Keyspace.queue_key(q, "active"), id])
      assert s != nil
    end

    and_ "worker B's delay with the live token 2 settles (re-scores the member to schedule, off active)" do
      assert :ok = Jobs.delay(conn, q, id, 2, 50)
      assert {:ok, "scheduled"} = Connector.command(conn, ["HGET", Keyspace.job_key(q, id), "state"])
      assert {:ok, nil} = Connector.command(conn, ["ZSCORE", Keyspace.queue_key(q, "active"), id])
    end

    but_ "a delay on a missing row answers {:error, :gone}" do
      assert {:error, :gone} = Jobs.delay(conn, q, BrandedId.generate!("JOB"), 1, 50)
    end
  end

  defp purge(q) do
    {:ok, conn} = Connector.start_link(port: 6390)
    {:ok, keys} = Connector.command(conn, ["KEYS", "emq:{" <> q <> "}:*"])
    if keys != [], do: {:ok, _} = Connector.command(conn, ["DEL" | keys])
    GenServer.stop(conn)
  end
end
