defmodule EchoMQ.Stories.BatchClaimStoryTest do
  @moduledoc """
  Acceptance criteria for the **Batch claim** spine (emq.5.1) — a high-throughput
  worker fetches up to `size` jobs in ONE atomic, server-clocked claim instead of
  one at a time (`EchoMQ.Jobs.claim_batch/4` over the NEW inline `@bclaim`
  count-variant `ZPOPMIN emq:{q}:pending` loop, the non-grouped generalization of
  the shipped `@gwclaim` multi-pop). An under-fill is a short batch (never a
  refusal, never a block); a paused queue answers `:empty` pending-untouched; one
  poisoned member is isolated to its own retry over the byte-frozen
  `@complete`/`@retry` (the batch is a CLAIM unit, not a RESOLUTION unit).

  Written in the `EchoMQ.Story` BDD DSL: every scenario below is a real ExUnit
  test driving `EchoMQ.Jobs` against Valkey on 6390, AND the source of
  `docs/echo_mq/stories/batch-claim.stories.md` (generated by `mix echo_mq.stories`).
  The exhaustive wire coverage lives in `test/batch_claim_test.exs`.
  """
  use EchoMQ.Story, feature: "Batch claim", async: false

  @moduletag :valkey

  alias EchoData.BrandedId
  alias EchoMQ.{Admin, Connector, Jobs, Keyspace}

  setup_all do
    :ok = EchoData.Snowflake.start(4)
    :ok
  end

  setup do
    {:ok, conn} = Connector.start_link(port: 6390)
    q = "emq.story.batch#{System.unique_integer([:positive])}"
    on_exit(fn -> purge(q) end)
    %{conn: conn, q: q}
  end

  scenario "a worker claims up to size jobs in one atomic, server-clocked pull", %{
    conn: conn,
    q: q
  } do
    given_ "a pending set flooded with 10 distinct mint-ordered JOB-ids" do
      ids =
        for _ <- 1..10 do
          id = BrandedId.generate!("JOB")
          {:ok, :enqueued} = Jobs.enqueue(conn, q, id, "work")
          id
        end
    end

    when_ "claim_batch is called once for size 4" do
      result = Jobs.claim_batch(conn, q, 4, 60_000)
    end

    then_ "it serves exactly the 4 oldest-mint members in mint order, each at attempts 1" do
      assert {:ok, members} = result
      assert length(members) == 4
      assert Enum.map(members, fn {id, _p, _a} -> id end) == Enum.take(ids, 4)
      assert Enum.all?(members, fn {_id, payload, att} -> payload == "work" and att == 1 end)
    end

    and_ "every served member is leased on ONE shared server-clock deadline (one TIME read)" do
      claimed = Enum.map(members, fn {id, _p, _a} -> id end)

      deadlines =
        Enum.map(claimed, fn id ->
          {:ok, s} = Connector.command(conn, ["ZSCORE", Keyspace.queue_key(q, "active"), id])
          s
        end)

      assert length(Enum.uniq(deadlines)) == 1
      assert hd(deadlines) != nil
    end
  end

  scenario "an under-fill is a short batch, and a paused queue answers empty untouched", %{
    conn: conn,
    q: q
  } do
    given_ "a pending set of 2 members and a claim requesting size 5" do
      ids =
        for _ <- 1..2 do
          id = BrandedId.generate!("JOB")
          {:ok, :enqueued} = Jobs.enqueue(conn, q, id, "u")
          id
        end
    end

    when_ "claim_batch is called for size 5 with only 2 pending" do
      short = Jobs.claim_batch(conn, q, 5, 60_000)
    end

    then_ "it answers the 2 available members (a short batch, never over-popping, never blocking)" do
      assert {:ok, members} = short
      assert length(members) == 2
      assert Enum.map(members, fn {id, _p, _a} -> id end) == ids
    end

    and_ "a subsequent claim on the now-empty pending set answers :empty" do
      assert :empty == Jobs.claim_batch(conn, q, 5, 60_000)
    end

    and_ "a claim against a queue paused queue-wide answers :empty with the pending set untouched" do
      pid = BrandedId.generate!("JOB")
      {:ok, :enqueued} = Jobs.enqueue(conn, q, pid, "p")
      :ok = Admin.pause(conn, q)
      assert :empty == Jobs.claim_batch(conn, q, 5, 60_000)
      assert {:ok, 1} = Connector.command(conn, ["ZCARD", Keyspace.queue_key(q, "pending")])
    end
  end

  scenario "one poisoned member is isolated to its own retry while the rest settle", %{
    conn: conn,
    q: q
  } do
    given_ "a batch of 3 members claimed in one call" do
      ids =
        for _ <- 1..3 do
          id = BrandedId.generate!("JOB")
          {:ok, :enqueued} = Jobs.enqueue(conn, q, id, "iso")
          id
        end

      {:ok, [poison | good]} = Jobs.claim_batch(conn, q, 3, 60_000)
      {poison_id, _p, poison_att} = poison
    end

    when_ "the poison member is retried (scheduled) and the other two complete" do
      assert {:ok, :scheduled} = Jobs.retry(conn, q, poison_id, poison_att, 5, 3, "poison")

      for {id, _p, att} <- good do
        assert :ok = Jobs.complete(conn, q, id, att)
      end
    end

    then_ "the poison row is scheduled with last_error kept; the other two rows are retired" do
      assert {:ok, "scheduled"} =
               Connector.command(conn, ["HGET", Keyspace.job_key(q, poison_id), "state"])

      assert {:ok, "poison"} =
               Connector.command(conn, ["HGET", Keyspace.job_key(q, poison_id), "last_error"])

      for {id, _p, _a} <- good do
        assert {:ok, 0} = Connector.command(conn, ["EXISTS", Keyspace.job_key(q, id)])
      end
    end

    and_ "after promote a fresh batch finds ONLY the poison, now at attempts 2 (its own token)" do
      Process.sleep(30)
      {:ok, 1} = Jobs.promote(conn, q, 10)
      assert {:ok, [{^poison_id, _p, 2}]} = Jobs.claim_batch(conn, q, 5, 60_000)
    end
  end

  defp purge(q) do
    {:ok, conn} = Connector.start_link(port: 6390)
    {:ok, keys} = Connector.command(conn, ["KEYS", "emq:{" <> q <> "}:*"])
    if keys != [], do: {:ok, _} = Connector.command(conn, ["DEL" | keys])
    GenServer.stop(conn)
  end
end
