defmodule EchoMQ.Stories.FlowsStoryTest do
  @moduledoc """
  Acceptance criteria for **Flows** — the single-queue parent/child flow. A parent
  becomes claimable only once its children complete (fan-in), and the parent handler
  reads its children's outcomes through `EchoMQ.Flows.children_values/3` (the results
  keyed by child id) and `EchoMQ.Flows.dependencies/3` (the outstanding count).

  Written in the `EchoMQ.Story` BDD DSL: every scenario below is a real ExUnit test
  driving `EchoMQ.Flows` against Valkey on 6390, AND the source of
  `docs/echo_mq/stories/flows.stories.md` (generated by `mix echo_mq.stories`).
  """
  use EchoMQ.Story, feature: "Flows", async: false

  @moduletag :valkey

  alias EchoData.BrandedId
  alias EchoMQ.{Connector, Flows, Jobs}

  setup_all do
    :ok = EchoData.Snowflake.start(4)
    :ok
  end

  setup do
    {:ok, conn} = Connector.start_link(port: 6390)
    q = "emq.story.flows#{System.unique_integer([:positive])}"
    on_exit(fn -> purge(q) end)
    %{conn: conn, q: q}
  end

  scenario "a parent runs only after its children, on the results they produced", %{conn: conn, q: q} do
    given_ "a single-queue flow of a parent and two children" do
      {:ok, {parent, [c1, c2]}} = add_flow(conn, q, ["one", "two"])
    end

    when_ "both children complete, each carrying a distinct result" do
      r1 = complete_next(conn, q)
      r2 = complete_next(conn, q)
    end

    then_ "children_values reads the real results back, keyed by child id" do
      assert {:ok, values} = Flows.children_values(conn, q, parent)
      assert values == %{c1 => r1, c2 => r2}
    end

    and_ "dependencies has counted down to zero outstanding" do
      assert {:ok, 0} = Flows.dependencies(conn, q, parent)
    end
  end

  scenario "the outstanding-child count falls by one for each completion", %{conn: conn, q: q} do
    given_ "a flow whose parent waits on three children" do
      {:ok, {parent, _children}} = add_flow(conn, q, ["a", "b", "c"])
    end

    then_ "dependencies starts at three and reaches zero as each child completes" do
      assert {:ok, 3} = Flows.dependencies(conn, q, parent)
      complete_next(conn, q)
      assert {:ok, 2} = Flows.dependencies(conn, q, parent)
      complete_next(conn, q)
      assert {:ok, 1} = Flows.dependencies(conn, q, parent)
      complete_next(conn, q)
      assert {:ok, 0} = Flows.dependencies(conn, q, parent)
    end
  end

  scenario "reading a flow's results is a pure, repeatable observation", %{conn: conn, q: q} do
    given_ "a flow with one completed child" do
      {:ok, {parent, [_c]}} = add_flow(conn, q, ["solo"])
      _r = complete_next(conn, q)
    end

    when_ "the parent reads children_values and dependencies twice" do
      first_values = Flows.children_values(conn, q, parent)
      first_deps = Flows.dependencies(conn, q, parent)
      second_values = Flows.children_values(conn, q, parent)
      second_deps = Flows.dependencies(conn, q, parent)
    end

    then_ "both reads return the same answer and leave the flow state untouched" do
      assert first_values == second_values
      assert first_deps == second_deps
    end
  end

  scenario "an ill-formed parent id is refused at the key boundary, before any wire", %{conn: conn, q: q} do
    then_ "children_values and dependencies both raise on a non-branded id" do
      assert_raise ArgumentError, fn -> Flows.children_values(conn, q, "not-branded") end
      assert_raise ArgumentError, fn -> Flows.dependencies(conn, q, "not-branded") end
    end
  end

  # -- helpers --------------------------------------------------------------

  # Add a flow of a parent + one child per payload; return Flows.add/3's result.
  defp add_flow(conn, q, child_payloads) do
    parent = BrandedId.generate!("JOB")
    children = Enum.map(child_payloads, &%{id: BrandedId.generate!("JOB"), payload: &1})
    Flows.add(conn, q, %{parent: %{id: parent, payload: "P"}, children: children})
  end

  # Claim the next pending child and complete it with a distinct result keyed to
  # its own id; return the result string.
  defp complete_next(conn, q) do
    {:ok, {id, _payload, token}} = Jobs.claim(conn, q, 60_000)
    result = "r-" <> id
    :ok = Jobs.complete(conn, q, id, token, result)
    result
  end

  defp purge(q) do
    {:ok, conn} = Connector.start_link(port: 6390)
    {:ok, keys} = Connector.command(conn, ["KEYS", "emq:{" <> q <> "}:*"])
    if keys != [], do: {:ok, _} = Connector.command(conn, ["DEL" | keys])
    GenServer.stop(conn)
  end
end
