defmodule EchoMQ.Stories.FlowsFailureStoryTest do
  @moduledoc """
  Acceptance criteria for **Flow failure handling** — the failure half of the
  single-queue parent/child flow (the completion half is `flows`). A flow no
  longer hangs when a child dies: by the child's policy the parent either
  **fails** (`fail_parent_on_failure`, the default — the parent moves to `dead`
  with the child recorded in its `:failed`) or **proceeds** past the failure
  (`ignore_dependency_on_failure` — the dead child is treated as a satisfied
  dependency, recorded in `:unsuccessful`, and the parent's handler reads the
  ignored failures through `EchoMQ.Flows.ignored_failures/3`). `add_bulk/3`
  submits many flows in one call, fail-closed per flow.

  Written in the `EchoMQ.Story` BDD DSL: every scenario below is a real ExUnit
  test driving `EchoMQ.Flows` against Valkey on 6390, AND the source of
  `docs/echo_mq/stories/flow-failure-handling.stories.md` (generated by
  `mix echo_mq.stories`). The same-queue propagation is atomic (one EVAL);
  the cross-queue propagation is eventually-consistent (delivered on the sweep
  tick), exhaustively covered in `test/flow_failure_test.exs`.
  """
  use EchoMQ.Story, feature: "Flow failure handling", async: false

  @moduletag :valkey

  alias EchoData.BrandedId
  alias EchoMQ.{Connector, Flows, Jobs}

  setup_all do
    :ok = EchoData.Snowflake.start(4)
    :ok
  end

  setup do
    {:ok, conn} = Connector.start_link(port: 6390)
    q = "emq.story.flowfail#{System.unique_integer([:positive])}"
    on_exit(fn -> purge(q) end)
    %{conn: conn, q: q}
  end

  scenario "a child that dies fails its parent by default, instead of hanging it forever", %{conn: conn, q: q} do
    given_ "a single-queue flow of a parent and one child, no policy declared (the default is fail-parent)" do
      {:ok, {parent, [child]}} = add_flow(conn, q, [%{id: BrandedId.generate!("JOB"), payload: "c"}])
    end

    when_ "the child exhausts its retries and lands in the morgue" do
      {:ok, {^child, _payload, 1}} = Jobs.claim(conn, q, 60_000)
      {:ok, :dead} = Jobs.retry(conn, q, child, 1, 10, 1, "boom")
    end

    then_ "the parent is failed too — moved to dead, the dead child recorded in its :failed" do
      assert {:ok, :dead} = state(conn, q, parent)
      assert {:ok, %{^child => "boom"}} = failed(conn, q, parent)
    end
  end

  scenario "a child marked ignore-on-failure lets the parent proceed once its siblings finish", %{conn: conn, q: q} do
    given_ "a flow of a parent and two children, one marked ignore_dependency_on_failure" do
      ignored = BrandedId.generate!("JOB")
      good = BrandedId.generate!("JOB")

      {:ok, {parent, [^ignored, ^good]}} =
        add_flow(conn, q, [
          %{id: ignored, payload: "i", ignore_dependency_on_failure: true},
          %{id: good, payload: "g"}
        ])
    end

    when_ "the ignored child dies and the other child completes" do
      {:ok, {^ignored, _, 1}} = Jobs.claim(conn, q, 60_000)
      {:ok, :dead} = Jobs.retry(conn, q, ignored, 1, 10, 1, "skip-me")
      {:ok, {^good, _, gtok}} = Jobs.claim(conn, q, 60_000)
      :ok = Jobs.complete(conn, q, good, gtok, "g-done")
    end

    then_ "the parent is released (not failed), and reads the ignored failure and the completed result apart" do
      assert {:ok, 0} = Flows.dependencies(conn, q, parent)
      assert {:ok, {^parent, "P", 1}} = Jobs.claim(conn, q, 60_000)
      assert {:ok, %{^ignored => "skip-me"}} = Flows.ignored_failures(conn, q, parent)
      assert {:ok, %{^good => "g-done"}} = Flows.children_values(conn, q, parent)
    end
  end

  scenario "a parent with no ignored failures reads an empty map", %{conn: conn, q: q} do
    then_ "ignored_failures returns an empty map for a parent that never ignored a failure" do
      assert {:ok, %{}} = Flows.ignored_failures(conn, q, BrandedId.generate!("JOB"))
    end
  end

  scenario "many flows are submitted in one call, fail-closed per flow", %{conn: conn, q: q} do
    given_ "two well-formed flows" do
      p1 = BrandedId.generate!("JOB")
      p2 = BrandedId.generate!("JOB")

      flows = [
        %{parent: %{id: p1, payload: "P1"}, children: [%{id: BrandedId.generate!("JOB"), payload: "a"}]},
        %{parent: %{id: p2, payload: "P2"}, children: [%{id: BrandedId.generate!("JOB"), payload: "b"}]}
      ]
    end

    when_ "they are added in bulk" do
      landed = Flows.add_bulk(conn, q, flows)
    end

    then_ "both parents land, each held awaiting its child" do
      assert {:ok, [{^p1, [_]}, {^p2, [_]}]} = landed
      assert {:ok, :awaiting_children} = state(conn, q, p1)
      assert {:ok, :awaiting_children} = state(conn, q, p2)
    end
  end

  # -- helpers --------------------------------------------------------------

  # Add a flow of a parent + the given child specs; return Flows.add/3's result.
  defp add_flow(conn, q, child_specs) do
    parent = BrandedId.generate!("JOB")
    Flows.add(conn, q, %{parent: %{id: parent, payload: "P"}, children: child_specs})
  end

  defp state(conn, q, id), do: EchoMQ.Metrics.get_job_state(conn, q, id)

  # Read the parent's :failed subkey as a %{child_id => error} map.
  defp failed(conn, q, parent) do
    case Connector.command(conn, ["HGETALL", EchoMQ.Keyspace.job_key(q, parent) <> ":failed"]) do
      {:ok, map} when is_map(map) -> {:ok, map}
      {:ok, [_ | _] = flat} -> {:ok, flat |> Enum.chunk_every(2) |> Map.new(fn [k, v] -> {k, v} end)}
      {:ok, []} -> {:ok, %{}}
      other -> other
    end
  end

  defp purge(q) do
    {:ok, conn} = Connector.start_link(port: 6390)
    {:ok, keys} = Connector.command(conn, ["KEYS", "emq:{" <> q <> "}:*"])
    if keys != [], do: {:ok, _} = Connector.command(conn, ["DEL" | keys])
    GenServer.stop(conn)
  end
end
