defmodule EchoMQ.Stories.GroupsStoryTest do
  @moduledoc """
  Acceptance criteria for **Groups** — fair, per-group admission and service
  (`EchoMQ.Lanes`). Jobs enqueue under a group identity; claims rotate strictly
  across the active lanes; a lane can be paused, resumed, and ceilinged.

  Written in the `EchoMQ.Story` BDD DSL: every scenario below is a real ExUnit test
  driving `EchoMQ.Lanes` against Valkey on 6390, AND the source of
  `docs/echo_mq/stories/groups.stories.md` (generated by `mix echo_mq.stories`).
  """
  use EchoMQ.Story, feature: "Groups", async: false

  @moduletag :valkey

  alias EchoData.BrandedId
  alias EchoMQ.{Connector, Jobs, Keyspace, Lanes}

  setup_all do
    :ok = EchoData.Snowflake.start(4)
    :ok
  end

  setup do
    {:ok, conn} = Connector.start_link(port: 6390)
    q = "emq.story.groups#{System.unique_integer([:positive])}"
    on_exit(fn -> purge(q) end)
    %{conn: conn, q: q}
  end

  scenario "a group admits work once, refuses duplicates and the wrong kind, and serves it under its identity", %{conn: conn, q: q} do
    given_ "a group and a job id" do
      group = BrandedId.generate!("PRT")
      id = BrandedId.generate!("JOB")
    end

    when_ "the job is enqueued under the group, then enqueued again, then a non-JOB id is offered" do
      first = Lanes.enqueue(conn, q, group, id, "cargo")
      repeat = Lanes.enqueue(conn, q, group, id, "again")
      wrong_kind = Lanes.enqueue(conn, q, group, BrandedId.generate!("ORD"), "x")
    end

    then_ "the first admits, the duplicate is refused idempotently, and the wrong kind is rejected" do
      assert {:ok, :enqueued} = first
      assert {:ok, :duplicate} = repeat
      assert {:error, :kind} = wrong_kind
    end

    and_ "claiming returns the job carrying its group" do
      assert {:ok, {^id, "cargo", 1, ^group}} = Lanes.claim(conn, q, 60_000)
    end
  end

  scenario "two lanes are served in strict rotation — the ring is the rota", %{conn: conn, q: q} do
    given_ "two groups, each holding two jobs" do
      [a, b] = for _ <- 1..2, do: BrandedId.generate!("PRT")

      for grp <- [a, b], _ <- 1..2 do
        {:ok, :enqueued} = Lanes.enqueue(conn, q, grp, BrandedId.generate!("JOB"), "r")
      end
    end

    when_ "four jobs are claimed in a row" do
      served =
        for _ <- 1..4 do
          {:ok, {_id, _payload, 1, grp}} = Lanes.claim(conn, q, 60_000)
          grp
        end
    end

    then_ "the lanes alternate strictly: a, b, a, b" do
      assert served == [a, b, a, b]
    end
  end

  scenario "pausing a lane parks its backlog intact; resuming returns it to rotation", %{conn: conn, q: q} do
    given_ "two groups, each holding two jobs" do
      [a, b] = for _ <- 1..2, do: BrandedId.generate!("PRT")

      for grp <- [a, b], _ <- 1..2 do
        {:ok, :enqueued} = Lanes.enqueue(conn, q, grp, BrandedId.generate!("JOB"), "p")
      end
    end

    when_ "lane a is paused and the queue is drained of what can be served" do
      :ok = Lanes.pause(conn, q, a)
      drained = drain(conn, q)
    end

    then_ "only lane b is served while a's backlog waits parked" do
      assert drained == [b, b]
      assert {:ok, 2} = Lanes.depth(conn, q, a)
    end

    and_ "resuming lane a returns it to rotation" do
      assert :ok = Lanes.resume(conn, q, a)
      assert {:ok, {_, _, 1, ^a}} = Lanes.claim(conn, q, 60_000)
    end
  end

  scenario "a lane's concurrency ceiling parks it until an in-flight job completes", %{conn: conn, q: q} do
    given_ "a lane capped at one in-flight job, holding two jobs" do
      a = BrandedId.generate!("PRT")
      :ok = Lanes.limit(conn, q, a, 1)
      j1 = BrandedId.generate!("JOB")
      {:ok, :enqueued} = Lanes.enqueue(conn, q, a, j1, "l")
      {:ok, :enqueued} = Lanes.enqueue(conn, q, a, BrandedId.generate!("JOB"), "l")
    end

    when_ "the first job is claimed and a second claim is attempted" do
      first = Lanes.claim(conn, q, 60_000)
      second = Lanes.claim(conn, q, 60_000)
    end

    then_ "the first claim serves j1 and the second finds the lane parked at its ceiling" do
      assert {:ok, {^j1, _, 1, ^a}} = first
      assert :empty = second
    end

    and_ "completing the in-flight job reopens the lane" do
      assert :ok = Jobs.complete(conn, q, j1, 1)
      assert {:ok, {_, _, 1, ^a}} = Lanes.claim(conn, q, 60_000)
    end
  end

  scenario "a group-scoped sweep recovers one tenant's lapsed leases into its lane, leaving a sibling's in active", %{conn: conn, q: q} do
    given_ "two tenants, each with one in-flight job claimed on a short lease" do
      g = BrandedId.generate!("PRT")
      h = BrandedId.generate!("PRT")
      id_g = BrandedId.generate!("JOB")
      id_h = BrandedId.generate!("JOB")
      {:ok, :enqueued} = Lanes.enqueue(conn, q, g, id_g, "g")
      {:ok, :enqueued} = Lanes.enqueue(conn, q, h, id_h, "h")
      {:ok, {^id_g, "g", 1, ^g}} = Lanes.claim(conn, q, 30)
      {:ok, {^id_h, "h", 1, ^h}} = Lanes.claim(conn, q, 30)
    end

    when_ "both leases lapse and only tenant g is reaped" do
      Process.sleep(80)
      recovered = Lanes.reap_group(conn, q, g)
    end

    then_ "g's member returns to its own lane while h's stays in active for the queue-wide reaper" do
      assert {:ok, 1} = recovered
      # g recovered into its lane g:<g>:pending
      assert {:ok, gs} = Connector.command(conn, ["ZSCORE", Keyspace.queue_key(q, "g:" <> g <> ":pending"), id_g])
      refute is_nil(gs)
      # h's expired member is LEFT in active -- the scoping filter
      assert {:ok, hs} = Connector.command(conn, ["ZSCORE", Keyspace.queue_key(q, "active"), id_h])
      refute is_nil(hs)
    end

    and_ "the recovered member is re-claimed under its own group with the attempt counter advanced" do
      assert {:ok, {^id_g, "g", 2, ^g}} = Lanes.claim(conn, q, 60_000)
    end
  end

  # -- helpers --------------------------------------------------------------

  # Claim until the queue reports `:empty`, returning the served groups in order.
  defp drain(conn, q), do: drain(conn, q, [])

  defp drain(conn, q, acc) do
    case Lanes.claim(conn, q, 60_000) do
      {:ok, {_id, _payload, _attempt, group}} -> drain(conn, q, [group | acc])
      :empty -> Enum.reverse(acc)
    end
  end

  defp purge(q) do
    {:ok, conn} = Connector.start_link(port: 6390)
    {:ok, keys} = Connector.command(conn, ["KEYS", "emq:{" <> q <> "}:*"])
    if keys != [], do: {:ok, _} = Connector.command(conn, ["DEL" | keys])
    GenServer.stop(conn)
  end
end
