defmodule EchoMQ.Stories.StreamConsumerStoryTest do
  @moduledoc """
  Acceptance criteria for the **Stream consumer** reader LAW (emq3.3, S2 the
  readers part 1) — a BEAM consumer group over a per-key event stream
  (`EchoMQ.StreamConsumer`), at-least-once with idempotent handlers, crash →
  re-delivery, the stored `id` field proven the polyglot receipt.

  The reader law's whole point is the at-least-once GUARANTEE: an entry whose
  handling crashed before it acked is NOT lost — it survives in the group's
  Pending Entries List (the PEL) and is RE-DELIVERED, by the consumer's own
  PEL-drain on restart (SELF) or by the `XAUTOCLAIM` beat (a dead PEER). A
  re-claimed entry returns OUT of real-time delivery order (the honest
  at-least-once cost), so the handler must be idempotent — the branded `id` is
  the dedup key (the BCS newer-wins discipline). Exactly-once is NOT claimed.

  Written in the `EchoMQ.Story` BDD DSL: every scenario below is a real ExUnit
  test driving `EchoMQ.StreamConsumer` against Valkey on 6390, AND the source of
  `docs/echo_mq/stories/stream-consumer.stories.md` (generated by `mix
  echo_mq.stories`). The exhaustive wire coverage lives in
  `test/stream_consumer_test.exs`; the conformance proof is the `stream_group`
  scenario (`EchoMQ.Conformance`). The crash-before-ack is DETERMINISTIC — a
  handler that returns `{:error, _}` leaves the entry un-acked exactly as a
  mid-handle crash would, with no real-time sleep gating a verdict.
  """
  use EchoMQ.Story, feature: "Stream consumer", async: false

  @moduletag :valkey

  alias EchoMQ.{Connector, Stream, StreamConsumer}

  setup_all do
    :ok = EchoData.Snowflake.start(4)
    :ok
  end

  setup do
    {:ok, conn} = Connector.start_link(port: 6390)
    q = "emq.story.stream#{System.unique_integer([:positive])}"
    on_exit(fn -> purge(q) end)
    %{conn: conn, q: q}
  end

  scenario "a consumer reads an entry and crashes before ack; the SAME branded id is re-delivered", %{
    conn: conn,
    q: q
  } do
    given_ "a stream with two EVT records and a consumer group reading from the head" do
      parent = self()
      keep = ok!(Stream.append(conn, q, "s", [{"seq", "keep"}]))
      crash = ok!(Stream.append(conn, q, "s", [{"seq", "crash"}]))
    end

    when_ "a consumer reads both but the handler crashes-before-ack on one (an {:error, _} verdict leaves it un-acked)" do
      # the crash entry returns {:error, _} (read, delivered, never acked -- a
      # crash-before-ack); the keep entry :ok. min_idle_ms 0 so the XAUTOCLAIM
      # beat re-delivers the un-acked crash entry to the SAME consumer.
      handler = fn job ->
        send(parent, {:delivered, job.id, job.attempts})
        if job.id == crash, do: {:error, :crashed_before_ack}, else: :ok
      end

      {:ok, c} =
        StreamConsumer.start_link(
          queue: q,
          stream: "s",
          group: "grp",
          consumer: "c1",
          group_start: :head,
          handler: handler,
          conn: own_lane(),
          beat_ms: 30,
          min_idle_ms: 0
        )
    end

    then_ "the un-acked entry is RE-DELIVERED -- the SAME branded id returns (never an ack-everything no-op)" do
      # both entries are delivered at least once
      assert_receive {:delivered, ^keep, _}, 3_000
      assert_receive {:delivered, ^crash, 1}, 3_000

      # the un-acked crash entry is re-delivered -- the SAME branded receipt, with
      # a higher attempts (the XPENDING delivery-count, NOT a failure count)
      assert_receive {:delivered, ^crash, redelivered_attempts}, 3_000
      assert redelivered_attempts >= 2

      assert :ok = StreamConsumer.stop(c)
    end

    and_ "the acked entry is NOT re-delivered (only the un-acked one survives in the PEL)" do
      # the keep entry was XACKed on its :ok verdict -- it left the PEL and is
      # never re-claimed; only the crash entry re-appears. refute it returns again.
      refute_receive {:delivered, ^keep, _}, 200
    end
  end

  scenario "a restarted consumer drains its OWN un-acked backlog first, then reads new (drain-PEL-first)", %{
    conn: conn,
    q: q
  } do
    given_ "a consumer that read its entries, left them un-acked, then was KILLED (they sit in its PEL)" do
      parent = self()
      key = Stream.stream_key(q, "s")
      backlog = for i <- 1..3, do: ok!(Stream.append(conn, q, "s", [{"seq", "b#{i}"}]))

      first_handler = fn job ->
        send(parent, {:first, job.id})
        {:error, :leave_unacked}
      end

      # min_idle_ms huge so NO XAUTOCLAIM beat masks the PEL-drain under test
      {:ok, c1} =
        StreamConsumer.start_link(
          queue: q,
          stream: "s",
          group: "grp",
          consumer: "c1",
          group_start: :head,
          handler: first_handler,
          conn: own_lane(),
          beat_ms: 1_000,
          min_idle_ms: 600_000
        )

      for b <- backlog, do: assert_receive({:first, ^b}, 3_000)
      wait_until(fn -> pel_size(conn, key, "grp") == 3 end)

      # crash the loop holding the un-acked entries (unlink first so :kill does
      # not take the test process -- a real crash under a supervisor would not).
      Process.unlink(c1)
      Process.exit(c1, :kill)
      wait_until(fn -> not Process.alive?(c1) end)
    end

    when_ "a NEW tail entry is appended AFTER the crash and the consumer restarts with the same name" do
      tail = ok!(Stream.append(conn, q, "s", [{"seq", "tail"}]))

      second_handler = fn job ->
        send(parent, {:second, job.id})
        :ok
      end

      {:ok, c2} =
        StreamConsumer.start_link(
          queue: q,
          stream: "s",
          group: "grp",
          consumer: "c1",
          group_start: :head,
          handler: second_handler,
          conn: own_lane(),
          beat_ms: 50,
          min_idle_ms: 600_000
        )
    end

    then_ "the restarted consumer handles its OWN prior un-acked backlog FIRST (by branded id), before the new tail" do
      recovered = for _ <- backlog, do: assert_receive_named(:second)
      assert recovered == backlog
      assert_receive {:second, ^tail}, 3_000
      assert :ok = StreamConsumer.stop(c2)
    end
  end

  scenario "a polyglot reader sees the same group state; the stored id field is the canonical receipt", %{
    conn: conn,
    q: q
  } do
    given_ "a stream with one EVT record appended via the BEAM writer, returning the branded receipt" do
      key = Stream.stream_key(q, "s")
      receipt = ok!(Stream.append(conn, q, "s", [{"k", "v"}]))
    end

    when_ "the entry is read with RAW XREADGROUP through the bare Connector (no Stream/StreamConsumer helpers)" do
      {:ok, "OK"} = Connector.command(conn, ["XGROUP", "CREATE", key, "grp", "0"])

      {:ok, reply} =
        Connector.command(conn, ["XREADGROUP", "GROUP", "grp", "polyglot", "COUNT", "10", "STREAMS", key, ">"])

      [xadd_id, fields] = first_entry(reply, key)
    end

    then_ "the entry's stored id field equals the branded receipt -- a non-BEAM client recovers the canonical id" do
      assert field_value(fields, "id") == receipt
    end

    and_ "a raw XACK through the bare Connector settles the entry against the SAME group state (one group, not two)" do
      assert {:ok, 1} = Connector.command(conn, ["XACK", key, "grp", xadd_id])
      assert pel_size(conn, key, "grp") == 0
    end
  end

  # -- helpers --------------------------------------------------------------

  # an exclusive private connector lane for one consumer (the :conn option).
  defp own_lane do
    {:ok, c} = Connector.start_link(port: 6390)
    c
  end

  defp ok!({:ok, v}), do: v

  # the PEL size for the group (the count of entries still pending) -- XPENDING
  # <key> <group> answers [count | ...]; 0 when the group has no pending entries.
  defp pel_size(conn, key, group) do
    case Connector.command(conn, ["XPENDING", key, group]) do
      {:ok, [n | _]} -> n
      _ -> 0
    end
  end

  defp wait_until(pred, tries \\ 600) do
    cond do
      pred.() -> :ok
      tries == 0 -> flunk("condition never held")
      true ->
        Process.sleep(5)
        wait_until(pred, tries - 1)
    end
  end

  # receive the next {tag, id} delivery (the drain-PEL-first ordering proof reads
  # deliveries one at a time so the recovered backlog order is observable).
  defp assert_receive_named(tag) do
    receive do
      {^tag, id} -> id
    after
      3_000 -> flunk("no #{inspect(tag)} message")
    end
  end

  # pull the first [xadd_id, fields] entry off an XREADGROUP reply (RESP3 map or
  # RESP2 nested-array stream->entries form -- the connection-dependent shape).
  defp first_entry(reply, key) when is_map(reply), do: reply |> Map.get(key) |> hd()

  defp first_entry(reply, key) when is_list(reply) do
    {^key, [entry | _]} = List.keyfind(reply, key, 0)
    entry
  end

  # the value of field `target` in a flat [k, v, k, v, ...] XADD field list.
  defp field_value([k, v | _], k), do: v
  defp field_value([_k, _v | rest], target), do: field_value(rest, target)
  defp field_value(_, _), do: nil

  defp purge(q) do
    {:ok, conn} = Connector.start_link(port: 6390)
    {:ok, keys} = Connector.command(conn, ["KEYS", "emq:{" <> q <> "}:*"])
    if keys != [], do: {:ok, _} = Connector.command(conn, ["DEL" | keys])
    GenServer.stop(conn)
  end
end
