defmodule EchoMQ.Stories.WirePipeCacheAsideStoryTest do
  @moduledoc """
  Acceptance criteria for **Wire — Pipe — cache-aside** (`EchoWire.Pipe`,
  EWR.1.1). A `%Pipe{}` writes a hot value with a TTL and reads it back in one
  flush — the cache-aside pattern (redis-patterns R1.01) over the owned wire.

  A `:valkey` ExUnit test driving `EchoWire.Pipe` end-to-end against Valkey on
  6390, AND the source of `docs/echo_mq/wire/stories/wire-pipe-cache-aside.stories.md`
  (generated by `mix echo_mq.stories`). A generated story exists only because
  this test passed (EWR.1.1-INV7).
  """
  use EchoMQ.Story, feature: "Wire — Pipe — cache-aside", async: false

  @moduletag :valkey

  alias EchoMQ.Connector
  alias EchoWire.Pipe

  setup do
    {:ok, conn} = Connector.start_link(port: 6390)
    k = "ewr.story.cache#{System.unique_integer([:positive])}"
    on_exit(fn -> purge(k) end)
    %{conn: conn, k: k}
  end

  scenario "a value written with a TTL is read back, and its expiry is live", %{conn: conn, k: k} do
    given_ "an empty cache key" do
      assert {:ok, [nil]} = conn |> Pipe.new() |> Pipe.get(k) |> Pipe.exec()
    end

    when_ "one pipe sets the value with a 60s TTL, reads it, and consults the TTL" do
      result =
        conn
        |> Pipe.new()
        |> Pipe.set(k, "alice", ex: 60)
        |> Pipe.get(k)
        |> Pipe.ttl(k)
        |> Pipe.exec()
    end

    then_ "the set acknowledges, the read returns the seeded value, and the TTL is positive" do
      assert {:ok, ["OK", "alice", ttl]} = result
      assert ttl > 0 and ttl <= 60
    end
  end

  defp purge(k) do
    {:ok, conn} = Connector.start_link(port: 6390)
    {:ok, _} = Connector.command(conn, ["DEL", k])
    GenServer.stop(conn)
  end
end
