defmodule EchoMQ.Stories.WirePipeCommandValueStoryTest do
  @moduledoc """
  Acceptance criteria for **Wire — Cmd — command value** (`EchoWire.Cmd` /
  `EchoWire.Command`, EWR.1.2). The fluent builder mints an immutable flagged
  command value, and that value runs **byte-identically** to the bare verb —
  the proof the advisory flags never reach the wire (EWR.1.2-INV4): a flagged
  `%Command{}` flushed via `Cmd.run/2` AND via `Pipe.command/2` returns exactly
  what the bare `Pipe` verb returns.

  A `:valkey` ExUnit test driving `EchoWire.Cmd` / `EchoWire.Command` /
  `EchoWire.Pipe` end-to-end against Valkey on 6390, AND the source of
  `docs/echo_mq/wire/stories/wire-cmd-command-value.stories.md` (generated by
  `mix echo_mq.stories`). A generated story exists only because this test
  passed (EWR.1.2-INV8).
  """
  use EchoMQ.Story, feature: "Wire — Cmd — command value", async: false

  @moduletag :valkey

  alias EchoMQ.Connector
  alias EchoWire.{Cmd, Command, Pipe}

  setup do
    {:ok, conn} = Connector.start_link(port: 6390)
    k = "ewr.story.cmd#{System.unique_integer([:positive])}"
    on_exit(fn -> purge(k) end)
    %{conn: conn, k: k}
  end

  scenario "a flagged GET command value runs byte-identically to the bare verb, via run/2 and via Pipe.command/2",
           %{conn: conn, k: k} do
    given_ "a seeded value and a built, readonly-flagged GET command value" do
      {:ok, _} = Connector.command(conn, ["SET", k, "alice"])
      cmd = Cmd.get(k) |> Cmd.build()
      # the value carries the advisory readonly flag + the key-slot
      assert Command.readonly?(cmd)
      assert Command.retryable?(cmd)
      assert Command.slot(cmd) == Command.slot_of(k)
    end

    when_ "the command is run three ways: Cmd.run/2, Pipe.command/2, and the bare Pipe verb" do
      cmd = Cmd.get(k) |> Cmd.build()
      via_run = Cmd.run(cmd, conn: conn)
      via_pipe_command = conn |> Pipe.new() |> Pipe.command(cmd) |> Pipe.exec()
      via_bare_verb = conn |> Pipe.new() |> Pipe.get(k) |> Pipe.exec()
    end

    then_ "all three return the identical reply — the advisory flag never reached the wire" do
      assert via_run == {:ok, ["alice"]}
      assert via_pipe_command == {:ok, ["alice"]}
      assert via_bare_verb == {:ok, ["alice"]}
      assert via_run == via_pipe_command
      assert via_pipe_command == via_bare_verb
    end
  end

  scenario "a built SET-with-TTL command value writes exactly as the bare verb (a write, advisory)",
           %{conn: conn, k: k} do
    given_ "a built SET command value with a 60s TTL — flagged a write" do
      cmd = Cmd.set(k) |> Cmd.value("bob") |> Cmd.ex(60) |> Cmd.build()
      assert Command.write?(cmd)
      refute Command.readonly?(cmd)
    end

    when_ "the SET command runs via Cmd.run/2, then the value + TTL are read back" do
      cmd = Cmd.set(k) |> Cmd.value("bob") |> Cmd.ex(60) |> Cmd.build()
      set_reply = Cmd.run(cmd, conn: conn)
      readback = conn |> Pipe.new() |> Pipe.get(k) |> Pipe.ttl(k) |> Pipe.exec()
    end

    then_ "the write acknowledges and the bare-verb equivalent would have produced the same state" do
      assert set_reply == {:ok, ["OK"]}
      assert {:ok, ["bob", ttl]} = readback
      assert ttl > 0 and ttl <= 60
    end
  end

  scenario "a list of built command values runs in one flush, replies in order (run/2 over a batch)",
           %{conn: conn, k: k} do
    given_ "three built command values: SET, GET, INCR on a sibling counter" do
      counter = k <> ":n"
      on_exit(fn -> purge(counter) end)

      cmds = [
        Cmd.set(k) |> Cmd.value("v") |> Cmd.build(),
        Cmd.get(k) |> Cmd.build(),
        Cmd.incr(counter) |> Cmd.build()
      ]
    end

    when_ "the batch runs through Cmd.run/2 in one flush" do
      result = Cmd.run(cmds, conn: conn)
    end

    then_ "the replies map one-to-one to the command order" do
      assert result == {:ok, ["OK", "v", 1]}
    end
  end

  scenario "an un-curated verb rides Command.raw/1 and runs wire-equivalently to a curated build",
           %{conn: conn, k: k} do
    given_ "a seeded value and a raw GET command value" do
      {:ok, _} = Connector.command(conn, ["SET", k, "carol"])
      raw = Command.raw(["GET", k])
      curated = Cmd.get(k) |> Cmd.build()
      assert raw.parts == curated.parts
    end

    when_ "both the raw value and the curated value run via Cmd.run/2" do
      via_raw = Cmd.run(Command.raw(["GET", k]), conn: conn)
      via_curated = Cmd.run(Cmd.get(k) |> Cmd.build(), conn: conn)
    end

    then_ "the raw and curated forms return the identical reply (the curated set is never a ceiling)" do
      assert via_raw == {:ok, ["carol"]}
      assert via_raw == via_curated
    end
  end

  defp purge(k) do
    {:ok, conn} = Connector.start_link(port: 6390)
    {:ok, _} = Connector.command(conn, ["DEL", k])
    GenServer.stop(conn)
  end
end
