defmodule EchoMQ.Stories.WirePipeErrorSplitStoryTest do
  @moduledoc """
  Acceptance criteria for **Wire — Result — error split** (`EchoWire.Result`,
  EWR.1.3). The two-tier classifier splits a **real** server error from the
  `:ok` replies, and names the transport tier — proven against Valkey on 6390:

  - the **server tier** is provoked for real (a `WRONGTYPE`: `SET` a string
    then `LPUSH` it, so Valkey itself returns `{:error_reply, "WRONGTYPE ..."}`
    in the second reply slot), and `classify/1` lands it as `:server_error`
    while `non_valkey_error/1` answers `nil`;
  - the **transport tier** is the Pipe's own `{:error, :empty_pipeline}`, which
    `classify/1` lands as `:transport_error`.

  A `:valkey` ExUnit test driving `EchoWire.Pipe` + `EchoWire.Result` together,
  AND the source of `docs/echo_mq/wire/stories/wire-result-error-split.stories.md`
  (generated by `mix echo_mq.stories`). A generated story exists only because
  this test passed, and the server-error story provokes a REAL error
  (EWR.1.3-INV7).
  """
  use EchoMQ.Story, feature: "Wire — Result — error split", async: false

  @moduletag :valkey

  alias EchoMQ.Connector
  alias EchoWire.{Pipe, Result}

  setup do
    {:ok, conn} = Connector.start_link(port: 6390)
    k = "ewr.story.err#{System.unique_integer([:positive])}"
    on_exit(fn -> purge(k) end)
    %{conn: conn, k: k}
  end

  scenario "a real WRONGTYPE is split from the :ok replies as a server error", %{conn: conn, k: k} do
    given_ "a pipe that SETs a string then LPUSHes it — the second command is a type error" do
      result =
        conn
        |> Pipe.new()
        |> Pipe.set(k, "a-string")
        |> Pipe.command(["LPUSH", k, "x"])
        |> Pipe.exec()
    end

    when_ "the exec return is classified" do
      classification = Result.classify(result)
      transport = Result.non_valkey_error(result)
      first_error = Result.error(result)
    end

    then_ "classify lands it as a server error at index 1, non_valkey_error is nil, error is the WRONGTYPE" do
      assert {:server_error, ["OK", {:error_reply, "WRONGTYPE" <> _}],
              [{1, {:error_reply, "WRONGTYPE" <> _}}]} = classification

      # a server error is NOT a transport error (NonValkeyError() semantics)
      assert transport == nil

      # error/1 (Error()) surfaces the server error when there is no transport failure
      assert {:error_reply, "WRONGTYPE" <> _} = first_error
    end
  end

  scenario "a fully clean flush classifies as :ok with no server errors", %{conn: conn, k: k} do
    given_ "a pipe of two well-typed string commands" do
      result =
        conn
        |> Pipe.new()
        |> Pipe.set(k, "v")
        |> Pipe.get(k)
        |> Pipe.exec()
    end

    when_ "the exec return is classified" do
      classification = Result.classify(result)
    end

    then_ "classify is :ok carrying the replies, and both error accessors answer nil/empty" do
      assert {:ok, ["OK", "v"]} = classification
      assert Result.non_valkey_error(result) == nil
      assert Result.error(result) == nil
      assert Result.server_errors(elem(result, 1)) == []
    end
  end

  scenario "a partial-batch flush keeps the :ok replies and indexes only the failing slots",
           %{conn: conn, k: k} do
    given_ "a pipe whose middle command is a WRONGTYPE against a string key" do
      result =
        conn
        |> Pipe.new()
        |> Pipe.set(k, "a-string")
        |> Pipe.command(["LPUSH", k, "x"])
        |> Pipe.get(k)
        |> Pipe.exec()
    end

    when_ "the server-error lens runs over the reply list" do
      {:ok, replies} = result
      slots = Result.server_errors(replies)
    end

    then_ "only the index-1 slot is a server error; the surrounding :ok replies are intact" do
      assert [{1, {:error_reply, "WRONGTYPE" <> _}}] = slots
      assert ["OK", {:error_reply, _}, "a-string"] = replies
    end
  end

  scenario "an empty pipe is the transport tier (empty_pipeline), never a server error", %{conn: conn} do
    given_ "an empty pipe over a live connection" do
      result = conn |> Pipe.new() |> Pipe.exec()
    end

    when_ "the (transport) return is classified" do
      classification = Result.classify(result)
      transport = Result.non_valkey_error(result)
    end

    then_ "classify is :transport_error and non_valkey_error returns the transport term" do
      assert {:transport_error, :empty_pipeline} = classification
      assert transport == {:error, :empty_pipeline}
      assert Result.error(result) == {:error, :empty_pipeline}
    end
  end

  defp purge(k) do
    {:ok, conn} = Connector.start_link(port: 6390)
    {:ok, _} = Connector.command(conn, ["DEL", k])
    GenServer.stop(conn)
  end
end
