#!/usr/bin/env bash
# Step 1 — environment. Exports the bench paths plus $REPO_ROOT (the fiberfx
# checkout) and the tool homes, writes them to $BENCH_HOME/.bcs-env so every other
# step sources one source of truth, and appends it to the login shell once.
set -euo pipefail

export BENCH_HOME="${BENCH_HOME:-$HOME/.bcs-bench}"
export REPO_ROOT="${REPO_ROOT:-$HOME/src/fiberfx}"     # the git checkout (NEW)
export UMBRELLA="${UMBRELLA:-$REPO_ROOT/echo}"          # the Elixir umbrella inside it
export GOROOT="${GOROOT:-/usr/local/go}"
export GOPATH="${GOPATH:-$HOME/go}"
# expectations the verifier/report check (lines drawn, not built from source)
export GO_VERSION="${GO_VERSION:-1.25}"                 # 1.25 line
export NODE_MIN="${NODE_MIN:-22}"                       # Node 22+
export VALKEY_MIN="${VALKEY_MIN:-8}"                    # floor 8.x
export VALKEY_PREFERRED="${VALKEY_PREFERRED:-9}"        # prefer the 9.x line
export ELIXIR_MIN="${ELIXIR_MIN:-1.15}"                 # functional floor (postgrex 0.22 needs >=1.15)
export ELIXIR_PIN="${ELIXIR_PIN:-1.18.4}"               # repo .tool-versions
export OTP_MIN="${OTP_MIN:-25}"                         # Elixir 1.18 runs on OTP 25-27

mkdir -p "$BENCH_HOME" "$GOPATH/bin"
ENVFILE="$BENCH_HOME/.bcs-env"
cat > "$ENVFILE" <<ENV
# generated by setup_env.sh — source of truth for the bench
export BENCH_HOME="$BENCH_HOME"
export REPO_ROOT="$REPO_ROOT"
export UMBRELLA="$UMBRELLA"
export GOROOT="$GOROOT"
export GOPATH="$GOPATH"
export GO_VERSION="$GO_VERSION"
export NODE_MIN="$NODE_MIN"
export VALKEY_MIN="$VALKEY_MIN"
export VALKEY_PREFERRED="$VALKEY_PREFERRED"
export ELIXIR_MIN="$ELIXIR_MIN"
export ELIXIR_PIN="$ELIXIR_PIN"
export OTP_MIN="$OTP_MIN"
export PATH="\$GOROOT/bin:\$GOPATH/bin:\$HOME/.local/bin:\$PATH"
ENV

if ! grep -q 'bcs-bench/.bcs-env' "$HOME/.bashrc" 2>/dev/null; then
  printf '\n# BCS bench env\n[ -f "%s" ] && . "%s"\n' "$ENVFILE" "$ENVFILE" >> "$HOME/.bashrc"
fi
# shellcheck disable=SC1090
. "$ENVFILE"

echo "== env =="
echo "   BENCH_HOME = $BENCH_HOME"
echo "   REPO_ROOT  = $REPO_ROOT   (clone target)"
echo "   UMBRELLA   = $UMBRELLA"
echo "   GOROOT     = $GOROOT   GOPATH = $GOPATH"
echo "   valkey     >= $VALKEY_MIN (prefer ${VALKEY_PREFERRED}.x)   elixir >= $ELIXIR_MIN (pin $ELIXIR_PIN)"
echo "   wrote $ENVFILE  (+ sourced from ~/.bashrc)"
